using System.Collections.Generic;
using System.Text;
using FlowX.Compiler.Emit;
using FlowX.Functions.Model;

namespace FlowX.Functions.Emit;

/// <summary>
/// Turns each flow's trigger attributes into the Azure Functions entry points a deployment
/// would otherwise hand-write.
/// </summary>
/// <remarks>
/// <para>
/// <strong>Every emitted method is one call, and that is the constraint rather than a
/// style.</strong> An entry point that decided anything would be a second copy of a decision
/// the runtime already makes — whether a redelivery is a duplicate, whether a message is
/// poison, which occurrence is due — living in generated text nobody tests. So each method
/// maps the platform's argument shape onto <c>FlowX.Hosting.FlowPushSeams</c> and settles from
/// what comes back, and there is nothing else in one.
/// </para>
/// <para>
/// <strong>Nothing here links against Azure.</strong> The attribute names are strings, written
/// fully qualified as <c>global::Microsoft.Azure.Functions.Worker.*</c>, and they bind against
/// the reference the consuming project declared. <see cref="FlowFunctionGenerator"/> looks that
/// reference up before asking for any of this, so a project without the worker SDK gets no
/// file, no type and no IL — <c>EndpointEmitter</c>'s arrangement with ASP.NET Core, one
/// platform over.
/// </para>
/// <para>
/// Pure: a model in, a string out, no Roslyn, so every emitted shape is testable by comparing
/// text.
/// </para>
/// </remarks>
public static class FunctionEmitter
{
    /// <summary>The file the emitted entry points are written to.</summary>
    public const string FileName = "FlowXFunctions.g.cs";

    private const string Worker = "global::Microsoft.Azure.Functions.Worker";

    private const string Seams = "global::FlowX.Hosting.FlowPushSeams";

    private const string Token = "global::System.Threading.CancellationToken";

    private const string Task = "global::System.Threading.Tasks.Task";

    private const string Provider = "global::System.IServiceProvider";

    /// <summary>Emits the entry points for every flow that declares a bindable trigger.</summary>
    /// <param name="assemblyName">The compilation's assembly name, which names the class.</param>
    /// <param name="functions">The entry points, in the order they should appear.</param>
    /// <param name="timers">
    /// One entry per sweep this worker wakes, which is at most two.
    /// </param>
    /// <param name="unbound">
    /// The declared triggers nothing is generated for. Emitted as a comment rather than
    /// dropped — see <see cref="EmitUnbound"/>.
    /// </param>
    /// <returns>The file's text.</returns>
    /// <exception cref="System.ArgumentNullException">An argument is null.</exception>
    public static string Emit(
        string assemblyName,
        IReadOnlyList<FunctionModel> functions,
        IReadOnlyList<TimerFunctionModel> timers,
        IReadOnlyList<UnboundTrigger> unbound)
    {
        if (functions is null)
        {
            throw new System.ArgumentNullException(nameof(functions));
        }

        if (timers is null)
        {
            throw new System.ArgumentNullException(nameof(timers));
        }

        if (unbound is null)
        {
            throw new System.ArgumentNullException(nameof(unbound));
        }

        var writer = new SourceWriter();

        writer.Line("// <auto-generated>");
        writer.Line("//     Generated by FlowX.Functions from the trigger attributes on this");
        writer.Line("//     assembly's flows — the same reading that produced the triggers block");
        writer.Line("//     of flowx.manifest.json.");
        writer.Line("//");
        writer.Line("//     Every method here is one call into the FlowX runtime. If one of them");
        writer.Line("//     ever contains a decision, that is a bug in the generator.");
        writer.Line("// </auto-generated>");
        writer.Line("#nullable enable");
        writer.Line();
        writer.Line("namespace FlowX.Generated");
        writer.OpenBrace();

        EmitClass(writer, ClassNameFor(assemblyName), functions, timers, unbound);

        writer.CloseBrace();

        return writer.ToString();
    }

    /// <summary>
    /// The class name for one assembly's entry points, e.g. <c>FunctionsSampleFunctions</c>.
    /// </summary>
    /// <remarks>
    /// Named from the assembly rather than fixed, for <c>ScheduleEmitter.ClassNameFor</c>'s
    /// reason: a deployment with two flow libraries would otherwise declare two
    /// <c>FlowX.Generated.FlowXFunctions</c> and the worker would fail to build with an
    /// ambiguity nobody can disambiguate.
    /// </remarks>
    /// <param name="assemblyName">The compilation's assembly name.</param>
    /// <returns>The class name.</returns>
    public static string ClassNameFor(string assemblyName)
    {
        var identifier = new StringBuilder();

        foreach (var character in assemblyName ?? string.Empty)
        {
            if (char.IsLetterOrDigit(character) || character == '_')
            {
                identifier.Append(character);
            }
        }

        if (identifier.Length == 0 || char.IsDigit(identifier[0]))
        {
            return "FlowXFunctions";
        }

        return identifier.Append("Functions").ToString();
    }

    private static void EmitClass(
        SourceWriter writer,
        string className,
        IReadOnlyList<FunctionModel> functions,
        IReadOnlyList<TimerFunctionModel> timers,
        IReadOnlyList<UnboundTrigger> unbound)
    {
        writer.Line("/// <summary>The serverless entry points this application's flows declare.</summary>");
        writer.Line("/// <remarks>");
        writer.Line("/// One method per bindable trigger, generated from the same reading of the");
        writer.Line("/// attribute that produced the <c>triggers</c> block of <c>flowx.manifest.json</c>.");
        writer.Line("/// The route, the topic and the group are therefore the manifest's own — there is");
        writer.Line("/// no second copy of them to drift, and each is a term the runtime derives an");
        writer.Line("/// instance id from.");
        writer.Line("/// </remarks>");
        writer.Line("public sealed class " + className);
        writer.OpenBrace();

        writer.Line("private readonly " + Seams + " _flowx;");
        writer.Line();
        writer.Line("private readonly " + Provider + " _services;");
        writer.Line();
        writer.Line("/// <summary>Takes the doors a pushed item comes through.</summary>");
        writer.Line("/// <param name=\"flowx\">Registered by <c>AddFlowX</c>.</param>");
        writer.Line("/// <param name=\"services\">Where each flow's generated dispatcher comes from.</param>");
        writer.Line("public " + className + "(" + Seams + " flowx, " + Provider + " services)");
        writer.OpenBrace();
        writer.Line("_flowx = flowx;");
        writer.Line("_services = services;");
        writer.CloseBrace();

        foreach (var function in functions)
        {
            writer.Line();
            EmitFunction(writer, function);
        }

        foreach (var timer in timers)
        {
            writer.Line();
            EmitTimer(writer, timer);
        }

        EmitUnbound(writer, unbound);

        writer.CloseBrace();
    }

    private static void EmitFunction(SourceWriter writer, FunctionModel function)
    {
        if (function.Binding == FunctionBinding.ServiceBus)
        {
            EmitServiceBus(writer, function);
        }
        else
        {
            EmitHttp(writer, function);
        }
    }

    /// <summary>
    /// An HTTP entry point: read the body, run the flow, write what the runtime said to write.
    /// </summary>
    /// <remarks>
    /// <c>HttpRequestData</c> rather than ASP.NET Core's <c>HttpRequest</c>, because the
    /// ASP.NET Core integration is an opt-in package and a generated file cannot require one
    /// the project may not have. The status and the body are both
    /// <c>FlowPushSeams.HttpAsync</c>'s answer — mapping an outcome onto a status is a decision
    /// and does not belong in generated text.
    /// </remarks>
    private static void EmitHttp(SourceWriter writer, FunctionModel function)
    {
        writer.Line("/// <summary><c>" + function.Method!.ToUpperInvariant() + " /" + function.Route +
            "</c> — runs <c>" + function.FlowId + "</c>.</summary>");
        writer.Line("/// <param name=\"request\">The request, as the worker hands it over.</param>");
        writer.Line("/// <param name=\"cancellationToken\">Cancels the flow.</param>");
        writer.Line("/// <returns>The response.</returns>");
        writer.Line("[" + Worker + ".Function(" + Quote(function.Name) + ")]");
        writer.Line("public async " + Task + "<" + Worker + ".Http.HttpResponseData> " + function.Name + "(");
        writer.Line("    [" + Worker + ".HttpTrigger(");
        writer.Line("        " + Worker + ".AuthorizationLevel.Anonymous,");
        writer.Line("        " + Quote(function.Method.ToLowerInvariant()) + ",");
        writer.Line("        Route = " + Quote(function.Route!) + ")]");
        writer.Line("        " + Worker + ".Http.HttpRequestData request,");
        writer.Line("    " + Token + " cancellationToken)");
        writer.OpenBrace();

        writer.Line("var outcome = await _flowx");
        writer.Line("    .HttpAsync<" + Global(function.InputTypeName!) + ", " + Global(function.OutputTypeName!) + ">(");
        writer.Line("        " + Global(function.FlowTypeName) + ".Plan,");
        writer.Line("        global::Microsoft.Extensions.DependencyInjection");
        writer.Line("            .ServiceProviderServiceExtensions");
        writer.Line("            .GetRequiredService<" + Global(function.FlowTypeName) + ".Dispatcher>(_services),");
        writer.Line("        request.Body,");
        writer.Line("        request.Headers,");
        writer.Line("        " + Global(function.FlowTypeName) + ".Projection,");
        writer.Line("        " + Global(function.JsonContextName!) + ".Default,");
        writer.Line("        " + (function.Idempotent ? "true" : "false") + ",");
        writer.Line("        cancellationToken)");
        writer.Line("    .ConfigureAwait(false);");
        writer.Line();
        // Called as static methods rather than as extensions, and that is a property of
        // generated code rather than a style: an extension method binds through a `using`, and
        // a generated file that emitted one would be relying on the user's file-scoped usings
        // reaching it. Both of these live on extension classes in the worker SDK.
        writer.Line("var response = " + Worker + ".Http.HttpRequestDataExtensions.CreateResponse(");
        writer.Line("    request, (global::System.Net.HttpStatusCode)outcome.Status);");
        writer.Line();
        writer.Line("response.Headers.Add(\"Content-Type\", outcome.ContentType);");
        writer.Line();
        // Emitted unconditionally because whether there is one is a run-time fact, not a
        // compile-time one: only a shed sets it, and the seam decides that per request. Still no
        // decision in generated text — the header's presence and its value are both the seam's.
        writer.Line("if (outcome.RetryAfterSeconds is { } retryAfterSeconds)");
        writer.OpenBrace();
        writer.Line("response.Headers.Add(");
        writer.Line("    \"Retry-After\",");
        writer.Line("    retryAfterSeconds.ToString(");
        writer.Line("        global::System.Globalization.CultureInfo.InvariantCulture));");
        writer.CloseBrace();
        writer.Line();
        writer.Line("await " + Worker + ".Http.HttpResponseDataExtensions");
        writer.Line("    .WriteStringAsync(response, outcome.Body, cancellationToken)");
        writer.Line("    .ConfigureAwait(false);");
        writer.Line();
        writer.Line("return response;");

        writer.CloseBrace();
    }

    /// <summary>
    /// A Service Bus entry point: admit the message, then settle it the way the platform does.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <strong><c>AutoCompleteMessages = false</c> is load-bearing.</strong> Left on, the
    /// platform completes a message the moment the function returns — including one the runtime
    /// said to requeue because nothing journalled it, which is the silent loss ADR-0036 exists
    /// to prevent. With it off, this method's three settles are the only ones, and each is the
    /// verb the returned disposition names.
    /// </para>
    /// <para>
    /// The switch is a translation and not a decision: <c>BusDisposition</c> has four members,
    /// the platform has three verbs, and <c>Started</c> and <c>Deduplicated</c> both mean the
    /// message is done with — which is what <c>FlowBusScan.DeliverAsync</c> also does with them
    /// on the pull path.
    /// </para>
    /// </remarks>
    private static void EmitServiceBus(SourceWriter writer, FunctionModel function)
    {
        const string Message = "global::Azure.Messaging.ServiceBus.ServiceBusReceivedMessage";
        const string Actions = "global::Microsoft.Azure.Functions.Worker.ServiceBusMessageActions";

        writer.Line("/// <summary><c>" + function.Topic + "</c> as <c>" + function.Group +
            "</c> — runs <c>" + function.FlowId + "</c>.</summary>");
        writer.Line("/// <param name=\"message\">The message, as the platform read it.</param>");
        writer.Line("/// <param name=\"actions\">How this platform settles the message it holds the lock on.</param>");
        writer.Line("/// <param name=\"cancellationToken\">Cancels the flow this admission starts.</param>");
        writer.Line("[" + Worker + ".Function(" + Quote(function.Name) + ")]");
        writer.Line("public async " + Task + " " + function.Name + "(");
        writer.Line("    [" + Worker + ".ServiceBusTrigger(");
        writer.Line("        " + Quote(function.Topic!) + ",");
        writer.Line("        " + Quote(function.Group!) + ",");
        writer.Line("        AutoCompleteMessages = false)]");
        writer.Line("        " + Message + " message,");
        writer.Line("    " + Actions + " actions,");
        writer.Line("    " + Token + " cancellationToken)");
        writer.OpenBrace();

        writer.Line("var admission = await _flowx");
        writer.Line("    .BusAsync(");
        writer.Line("        " + Quote(function.FlowId) + ",");
        writer.Line("        " + Quote(function.Topic!) + ",");
        writer.Line("        message.MessageId,");
        writer.Line("        message.Subject,");
        writer.Line("        message.ApplicationProperties.TryGetValue(\"schema-version\", out var schema)");
        writer.Line("            ? schema as string");
        writer.Line("            : null,");
        writer.Line("        message.PartitionKey,");
        writer.Line("        message.Body.ToString(),");
        writer.Line("        message.ApplicationProperties.TryGetValue(\"tenant-id\", out var tenant)");
        writer.Line("            ? tenant as string");
        writer.Line("            : null,");
        writer.Line("        message.LockToken,");
        writer.Line("        (int)message.DeliveryCount,");
        writer.Line("        cancellationToken)");
        writer.Line("    .ConfigureAwait(false);");
        writer.Line();
        writer.Line("switch (admission.Disposition)");
        writer.OpenBrace();
        writer.Line("case global::FlowX.Hosting.BusDisposition.DeadLetter:");
        writer.Line("    await actions");
        writer.Line("        .DeadLetterMessageAsync(");
        writer.Line("            message,");
        writer.Line("            deadLetterReason: \"flowx.poison\",");
        writer.Line("            deadLetterErrorDescription: admission.Reason,");
        writer.Line("            cancellationToken: cancellationToken)");
        writer.Line("        .ConfigureAwait(false);");
        writer.Line();
        writer.Line("    break;");
        writer.Line();
        writer.Line("case global::FlowX.Hosting.BusDisposition.Requeue:");
        writer.Line("    await actions");
        writer.Line("        .AbandonMessageAsync(message, cancellationToken: cancellationToken)");
        writer.Line("        .ConfigureAwait(false);");
        writer.Line();
        writer.Line("    break;");
        writer.Line();
        writer.Line("default:");
        writer.Line("    await actions");
        writer.Line("        .CompleteMessageAsync(message, cancellationToken)");
        writer.Line("        .ConfigureAwait(false);");
        writer.Line();
        writer.Line("    break;");
        writer.CloseBrace();

        writer.CloseBrace();
    }

    /// <summary>
    /// A timer entry point: one sweep pass, on the platform's clock.
    /// </summary>
    /// <remarks>
    /// <see cref="FunctionModel.PollingCron"/> says why the platform's expression is a poll
    /// rather than the declared schedule. The declared one is fired by the sweep, from the
    /// model this generator read, which is what keeps one schedule from becoming two.
    /// </remarks>
    private static void EmitTimer(SourceWriter writer, TimerFunctionModel timer)
    {
        var change = timer.Pass == TimerPass.Change;
        var pass = change ? "ChangeAsync" : "ScheduleAsync";
        var subject = change ? "the change feed" : "the declared schedules";

        writer.Line("/// <summary>Wakes this host so " + subject + " can be read.</summary>");
        writer.Line("/// <remarks>");
        writer.Line("/// One firing runs one pass over every declaration below, because that is what");
        writer.Line("/// the sweep does — a timer per flow would run the same whole pass once per");
        writer.Line("/// declaration and reach nothing a single one does not.");

        foreach (var flowId in timer.FlowIds)
        {
            writer.Line("/// <para><c>" + flowId + "</c></para>");
        }

        writer.Line("/// </remarks>");
        writer.Line("/// <param name=\"timer\">The platform's firing, which nothing here reads.</param>");
        writer.Line("/// <param name=\"cancellationToken\">Cancels the pass, and every flow it started.</param>");
        writer.Line("[" + Worker + ".Function(" + Quote(timer.Name) + ")]");
        writer.Line("public " + Task + " " + timer.Name + "(");
        writer.Line("    [" + Worker + ".TimerTrigger(" + Quote(FunctionModel.PollingCron) + ")]");
        writer.Line("        " + Worker + ".TimerInfo timer,");
        writer.Line("    " + Token + " cancellationToken) =>");
        writer.Line("    _flowx." + pass + "(cancellationToken).AsTask();");
    }

    /// <summary>
    /// Records every declared trigger that produced no entry point, in the generated file.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <strong>A comment rather than silence, and rather than a diagnostic.</strong> A flow
    /// declaring <c>[StreamTrigger]</c> in a Functions project has declared something this
    /// package does not serve, and the reader who goes looking for the entry point needs the
    /// answer where they are looking — in the file — not in a build log from three weeks ago.
    /// A diagnostic was the alternative and is wrong here: nothing is defective. The
    /// declaration is legitimate, the manifest publishes it, and the ASP.NET host serves it;
    /// only this deployment shape does not.
    /// </para>
    /// <para>
    /// The reason is per trigger, because the reasons differ. <c>Manual</c> and <c>Cli</c> have
    /// no address for a platform to bind at all; <c>Stream</c> has one and needs state a host
    /// that scales to zero does not keep.
    /// </para>
    /// </remarks>
    private static void EmitUnbound(SourceWriter writer, IReadOnlyList<UnboundTrigger> unbound)
    {
        if (unbound.Count == 0)
        {
            return;
        }

        writer.Line();
        writer.Line("// Declared, and deliberately not bound here:");

        foreach (var trigger in unbound)
        {
            writer.Line("//");
            writer.Line("//   " + trigger.Kind + " on '" + trigger.FlowId + "'");
            writer.Line("//     " + trigger.Reason);
        }
    }

    private static string Global(string typeName) => "global::" + typeName;

    private static string Quote(string value) =>
        "\"" + value.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
}
