using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using FlowX.Compiler.Model;

namespace FlowX.Compiler.Emit;

/// <summary>
/// Turns a <see cref="FlowModel"/> into the C# a flow needs at run time: its
/// compiled <c>ExecutionPlan</c> and its <c>IStepDispatcher</c>.
/// </summary>
/// <remarks>
/// <para>
/// Pure. Takes a model, returns a string, touches nothing else — which is what
/// makes every emitted shape testable by comparing text, with no compilation and
/// no Roslyn host. That is the second half of the R1 mitigation.
/// </para>
/// <para>
/// The emitted dispatcher is the reason the engine can stay type-agnostic. It holds
/// each step's typed input and output in its own fields and switches on the step
/// index, so nothing is boxed and the engine never learns what a
/// <c>ReserveRequest</c> is. See <c>IStepDispatcher</c> for why that split exists.
/// </para>
/// </remarks>
public static class FlowEmitter
{
    /// <summary>The header every generated file carries.</summary>
    public const string Header =
        "// <auto-generated>\n" +
        "//     Generated by FlowX.Compiler from the Define method of this flow.\n" +
        "//\n" +
        "//     This file is real C#, on disk, with line directives back to your source.\n" +
        "//     Set a breakpoint in it. If it is hard to read, that is a bug in the\n" +
        "//     generator, not something you are supposed to put up with.\n" +
        "// </auto-generated>\n";

    /// <summary>The file name this model's generated source should be written to.</summary>
    public static string FileNameFor(FlowModel flow)
    {
        if (flow is null)
        {
            throw new System.ArgumentNullException(nameof(flow));
        }

        return flow.FullTypeName + ".Flow.g.cs";
    }

    /// <summary>Emits the plan and dispatcher for one flow.</summary>
    /// <param name="flow">The flow to render.</param>
    /// <remarks>
    /// The overload for a compilation that declares no serialiser context, and for the tests
    /// that are about everything except the outbox. A flow whose events cannot be serialised
    /// gets a dispatcher that describes no event, which is exactly the state
    /// <c>FLOWX1024</c> reports.
    /// </remarks>
    public static string Emit(FlowModel flow) => Emit(flow, []);

    /// <summary>Emits the plan and dispatcher for one flow.</summary>
    /// <param name="flow">The flow to render.</param>
    /// <param name="jsonContexts">
    /// Every <c>JsonSerializerContext</c> the compilation declares. An <c>.Emit</c> step's
    /// event body is written through the one that declares its contract, exactly as an
    /// endpoint's request body is — see <c>EndpointEmitter</c>.
    /// </param>
    public static string Emit(FlowModel flow, IReadOnlyList<JsonContextModel> jsonContexts)
    {
        if (flow is null)
        {
            throw new System.ArgumentNullException(nameof(flow));
        }

        if (jsonContexts is null)
        {
            throw new System.ArgumentNullException(nameof(jsonContexts));
        }

        var staged = StageableEvents(flow, jsonContexts);
        var writer = new SourceWriter();

        writer.Line(Header.TrimEnd('\n'));
        writer.Line("#nullable enable");
        writer.Line();
        writer.Line("using System;");
        writer.Line("using System.Threading;");
        writer.Line("using System.Threading.Tasks;");
        writer.Line("using FlowX;");
        writer.Line("using FlowX.Runtime;");

        // The author's usings, so a copied .Return(...) lambda resolves the same names
        // here that it resolved where it was written. Skipped when already emitted above.
        foreach (var directive in flow.Usings.Where(u => !EmittedUsings.Contains(u)))
        {
            writer.Line(directive);
        }

        writer.Line();

        var hasNamespace = !string.IsNullOrEmpty(flow.ContainingNamespace);

        if (hasNamespace)
        {
            writer.Line("namespace " + flow.ContainingNamespace);
            writer.OpenBrace();
        }

        EmitFlowPartial(writer, flow, staged);

        if (hasNamespace)
        {
            writer.CloseBrace();
        }

        return writer.ToString();
    }

    private static void EmitFlowPartial(
        SourceWriter writer, FlowModel flow, IReadOnlyList<StagedEvent> staged)
    {
        writer.Line("/// <summary>Compiled plan and dispatcher for <c>" + flow.FlowId + "</c>.</summary>");
        writer.Line("partial class " + flow.TypeName);
        writer.OpenBrace();

        EmitDescriptors(writer, flow);
        writer.Line();
        EmitTypedContext(writer, flow, staged);
        EmitStepInputs(writer, flow);
        EmitConditions(writer, flow);
        EmitSelectors(writer, flow);
        EmitIterations(writer, flow);
        EmitSubFlowMaps(writer, flow);
        EmitEvents(writer, flow, staged);
        EmitFailures(writer, flow);
        EmitPlan(writer, flow);
        writer.Line();
        EmitProjection(writer, flow);
        EmitSensitiveMembers(writer, flow);
        EmitDispatcher(writer, flow, staged);

        writer.CloseBrace();
    }

    /// <summary>
    /// Emits the flow's output projection from its <c>.Return(...)</c> clause.
    /// </summary>
    /// <remarks>
    /// <para>
    /// A <c>static readonly</c> field, not a method or a lambda built per call: the engine
    /// takes it as a <c>Func</c>, and a field is allocated once at type initialisation, so
    /// passing it costs nothing and the zero-allocation budget survives contact with the
    /// feature that gives a flow an answer to return.
    /// </para>
    /// <para>
    /// <strong>Wrapped in <c>FlowContext.Untyped&lt;TIn, TOut&gt;(...)</c> rather than
    /// copied bare.</strong> The author's expression is written against
    /// <c>FlowContext&lt;TIn&gt;</c> — that is the parameter type <c>.Return(...)</c>
    /// declares, and the only one on which <c>ctx.Input</c> resolves — while
    /// <c>FlowEngine.ExecuteAsync</c> and <c>MapFlow</c> both take a
    /// <c>Func&lt;FlowContext, TOut&gt;</c>. One call adapts the first shape to the
    /// second; retyping the engine would push a generic parameter through two packages to
    /// save it. The field is still one field, still <c>static readonly</c>, and still the
    /// author's own text inside a <c>#line</c> pair.
    /// </para>
    /// </remarks>
    private static void EmitProjection(SourceWriter writer, FlowModel flow)
    {
        if (flow.ReturnProjection is null)
        {
            return;
        }

        writer.Line("/// <summary>Projects the flow's output from the finished context.</summary>");
        writer.Line("/// <remarks>");
        writer.Line("/// Your <c>.Return(...)</c> expression, copied verbatim. The engine runs it while");
        writer.Line("/// the pooled context is still rented, which is why it can read the context at all.");
        writer.Line("/// </remarks>");
        EmitLineDirective(writer, flow.ReturnLocation);
        writer.Line(
            "public static readonly Func<FlowContext, " + flow.OutputTypeName + "> Projection = " +
            "FlowContext.Untyped<" + flow.InputTypeName + ", " + flow.OutputTypeName + ">(" +
            flow.ReturnProjection + ");");
        EmitLineDirectiveEnd(writer, flow.ReturnLocation);
        writer.Line();
    }

    /// <summary>
    /// Emits the one-line conversion from the engine's context to the typed view every
    /// copied expression is written against.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <strong>This is the whole of the fix for <c>ctx.Input</c>.</strong> Every delegate on
    /// <c>IFlowBuilder</c> takes a <c>Func&lt;FlowContext&lt;TIn&gt;, …&gt;</c>, and this
    /// generator used to copy the author's lambda into a field typed at the non-generic
    /// <c>FlowContext</c> — on which <c>Input</c> is not declared. A predicate that read it
    /// compiled in the author's editor and then failed with CS1061 inside generated source.
    /// The fields below are now typed at the view, and this is what produces one.
    /// </para>
    /// <para>
    /// <c>FlowContext&lt;TIn&gt;</c> is a <c>readonly struct</c> wrapping a reference, so
    /// this allocates nothing and the JIT inlines it away. It takes the context it is
    /// handed rather than a cast, which is what makes a predicate inside a <c>ForEach</c>
    /// body work: there the context is the iteration's scope, not the flow's own.
    /// </para>
    /// </remarks>
    private static void EmitTypedContext(
        SourceWriter writer, FlowModel flow, IReadOnlyList<StagedEvent> staged)
    {
        if (!NeedsTypedContext(flow) && staged.Count == 0)
        {
            return;
        }

        writer.Line("/// <summary>The typed view your expressions receive: a struct over whatever");
        writer.Line("/// context is current, so it allocates nothing.</summary>");
        writer.Line(
            "private static FlowContext<" + flow.InputTypeName + "> Typed(FlowContext ctx) => " +
            "new FlowContext<" + flow.InputTypeName + ">(ctx);");
        writer.Line();
    }

    /// <summary>
    /// Whether the dispatcher has a call site that needs the view.
    /// </summary>
    /// <remarks>
    /// The <c>.Return(...)</c> projection deliberately does not count: it is adapted once
    /// at its own field through <c>FlowContext&lt;TIn&gt;.Untyped(...)</c>, so a linear
    /// flow — which is most flows — gets no helper it would only call from one place.
    /// </remarks>
    private static bool NeedsTypedContext(FlowModel flow) =>
        flow.AllSteps.Any(s => s.Kind is StepKindModel.Condition or StepKindModel.Switch
            or StepKindModel.ForEach or StepKindModel.SubFlow || s.HasInputMapping);

    /// <summary>The flow's explicitly mapped steps, ascending by flat index.</summary>
    private static System.Collections.Generic.List<StepModel> MappedSteps(FlowModel flow) => flow.AllSteps
        .Where(s => s.HasInputMapping)
        .OrderBy(s => s.Index)
        .ToList();

    /// <summary>An <c>.Emit</c> step this build can turn into an outbox row.</summary>
    private sealed class StagedEvent
    {
        public StagedEvent(StepModel step, string jsonContextTypeName)
        {
            Step = step;
            JsonContextTypeName = jsonContextTypeName;
        }

        /// <summary>The emit step.</summary>
        public StepModel Step { get; }

        /// <summary>The single serialiser context declaring its contract.</summary>
        public string JsonContextTypeName { get; }
    }

    /// <summary>
    /// The flow's <c>.Emit</c> steps that can actually be staged, ascending by flat index.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Three conditions, and each one is a <c>FLOWX1024</c> when it fails. <strong>The flow
    /// must be <c>Durable</c></strong> — an ephemeral execution keeps no journal, so there is
    /// no transaction for the row to be part of and staging it anywhere else would be the
    /// dual write the outbox exists to remove. <strong>The step must have a factory and a
    /// resolved contract</strong>, which is only false in a half-typed buffer.
    /// <strong>Exactly one <c>JsonSerializerContext</c> in the compilation must declare the
    /// contract</strong>: <c>JournalPayload.Of</c> takes a <c>JsonTypeInfo&lt;T&gt;</c> and has
    /// no overload that reflects over a type, which is what keeps the write path trim- and
    /// NativeAOT-safe (constraint C2, ADR-0008).
    /// </para>
    /// <para>
    /// None and several are the same answer, for the reason <c>EndpointEmitter</c> gives:
    /// picking the first of several would make the event body's shape depend on file order.
    /// </para>
    /// </remarks>
    private static List<StagedEvent> StageableEvents(
        FlowModel flow, IReadOnlyList<JsonContextModel> jsonContexts)
    {
        var staged = new List<StagedEvent>();

        if (!string.Equals(flow.Profile, "Durable", System.StringComparison.Ordinal))
        {
            return staged;
        }

        foreach (var step in flow.AllSteps
            .Where(s => s.Kind == StepKindModel.Emit)
            .OrderBy(s => s.Index))
        {
            if (step.EventFactory is null || step.EventContractTypeName is null)
            {
                continue;
            }

            var context = SingleContextFor(jsonContexts, step.EventContractTypeName);

            if (context is not null)
            {
                staged.Add(new StagedEvent(step, context));
            }
        }

        return staged;
    }

    /// <summary>The single serialiser context declaring a contract, or <c>null</c>.</summary>
    internal static string? SingleContextFor(
        IReadOnlyList<JsonContextModel> jsonContexts, string contractTypeName)
    {
        string? found = null;

        foreach (var candidate in jsonContexts.Where(c => c.Declares(contractTypeName)))
        {
            if (found is not null)
            {
                return null;
            }

            found = candidate.TypeName;
        }

        return found;
    }

    /// <summary>
    /// Emits one <c>static readonly</c> delegate per <c>.Emit(...)</c> factory.
    /// </summary>
    /// <remarks>
    /// A field, for the reason the predicates and the selectors are: it is built once at type
    /// initialisation, so describing a step costs no delegate. The author's own expression,
    /// copied verbatim inside a <c>#line</c> pair, so a breakpoint on the event body lands on
    /// the body they wrote.
    /// <para>
    /// It runs at the step boundary, immediately before the commit, rather than when the step
    /// executed. That is the same place the journal's other payloads are built, and it is
    /// sound for the same reason a compensation may re-run a step's input mapping: the
    /// expression is pure and deterministic (FLOWX1011), and it reads the scope the step
    /// itself ran under.
    /// </para>
    /// </remarks>
    private static void EmitEvents(
        SourceWriter writer, FlowModel flow, IReadOnlyList<StagedEvent> staged)
    {
        if (staged.Count == 0)
        {
            return;
        }

        writer.Line("/// <summary>Event bodies, built once at type initialisation.</summary>");
        writer.Line("/// <remarks>");
        writer.Line("/// Each is your <c>.Emit&lt;TEvent&gt;(...)</c> expression, copied verbatim. It is");
        writer.Line("/// evaluated at the step boundary and the result is staged into the outbox by the");
        writer.Line("/// same transaction that records the step, so the state and the event commit");
        writer.Line("/// together or not at all.");
        writer.Line("/// </remarks>");
        writer.Line("private static class Events");
        writer.OpenBrace();

        foreach (var staging in staged)
        {
            EmitLineDirective(writer, staging.Step.EventFactoryLocation);
            writer.Line(
                "public static readonly Func<FlowContext<" + flow.InputTypeName + ">, " +
                staging.Step.EventContractTypeName + "> Step" + staging.Step.Index + " = " +
                staging.Step.EventFactory + ";");
            EmitLineDirectiveEnd(writer, staging.Step.EventFactoryLocation);
        }

        writer.CloseBrace();
        writer.Line();
    }

    /// <summary>
    /// Emits <c>DescribeStep</c>: the outbox row an <c>Emit</c> step contributes to its own
    /// commit.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <strong>Here rather than on the engine, for the reason nothing else typed is on the
    /// engine either.</strong> <c>JournalPayload.Of</c> needs a <c>JsonTypeInfo&lt;TEvent&gt;</c>
    /// and only generated code can name one; the step loop holds a
    /// <c>Dictionary&lt;Type, object&gt;</c> and knows no contract types at all.
    /// </para>
    /// <para>
    /// <strong>The payload carries the flow's <c>SensitiveMembers</c>.</strong> An event body
    /// is a second sink for a marked member and the worse of the two — a journal row stays in
    /// one table, where a broker fans the event out to every consumer. The control is
    /// inherited rather than re-implemented: the payload is a <c>JournalPayload</c>, which has
    /// no accessor for its value and only leaves through <c>ToJson</c>, which redacts.
    /// </para>
    /// <para>
    /// <strong>The partition key is the instance id.</strong> ADR-0018 offers ordering per
    /// <c>partition_key</c> and no global order, so this is what makes "two events from one
    /// order arrive in the order that order staged them" true. There is no DSL surface for
    /// choosing a business key yet; when there is, it replaces this expression and nothing
    /// else.
    /// </para>
    /// <para>
    /// Emitted only for a flow that has at least one stageable event. A dispatcher that
    /// describes nothing inherits <c>IStepDispatcher</c>'s default, which returns
    /// <c>StepJournalEntry.Nothing</c> — a truthful, resumable record without payloads.
    /// </para>
    /// </remarks>
    private static void EmitDispatcherDescribe(
        SourceWriter writer, IReadOnlyList<StagedEvent> staged)
    {
        writer.Line("/// <inheritdoc />");
        writer.Line("public StepJournalEntry DescribeStep(int stepIndex, FlowContext ctx)");
        writer.OpenBrace();
        writer.Line("switch (stepIndex)");
        writer.OpenBrace();

        foreach (var staging in staged)
        {
            writer.Line("case " + staging.Step.Index + ":");
            writer.OpenBrace();
            writer.Line("return StepJournalEntry.OfEvent(new OutboxWrite");
            writer.OpenBrace();
            writer.Line("Type = " + Quote(staging.Step.EventType!) + ",");
            writer.Line("SchemaVersion = " + Quote(ManifestWriter.EventSchemaVersion) + ",");
            writer.Line();
            writer.Line("// Per-key ordering, and the key is the instance: ADR-0018 offers no");
            writer.Line("// global order, so this is the ordering a consumer actually gets.");
            writer.Line("PartitionKey = ctx.FlowInstanceId,");
            writer.Line();
            writer.Line("// The generated context writes it, and SensitiveMembers keeps a");
            writer.Line("// marked member out of the body a broker fans out.");
            writer.Line("Payload = JournalPayload.Of(");
            writer.Line("    Events.Step" + staging.Step.Index + "(Typed(ctx)),");
            writer.Line("    global::" + staging.JsonContextTypeName + ".Default,");
            writer.Line("    SensitiveMembers),");
            writer.CloseBrace(");");
            writer.CloseBrace();
        }

        writer.Line("default:");
        writer.OpenBrace();
        writer.Line("// Every other step describes nothing: no payload writer exists yet, and");
        writer.Line("// a journal of step boundaries without payloads is truthful and resumable.");
        writer.Line("return StepJournalEntry.Nothing;");
        writer.CloseBrace();

        writer.CloseBrace();
        writer.CloseBrace();
    }

    /// <summary>
    /// Emits one <c>static readonly</c> delegate per
    /// <c>.Step&lt;TCapability, TStepIn&gt;(map)</c> input mapping.
    /// </summary>
    /// <remarks>
    /// <para>
    /// A field, for the reason the predicates, the selectors and the sub-flow mappings are:
    /// built once at type initialisation rather than once per execution, so a mapped step
    /// costs no delegate allocation on the hot path. Budget B2 is a hard zero and a lambda
    /// built at the call site would have lost it for every flow that maps a step.
    /// </para>
    /// <para>
    /// <strong>Where the mapped value lives: nowhere but the call site.</strong> The
    /// dispatcher passes the result of this delegate straight to the capability and does
    /// not write it into the state bag. The bag is keyed on <c>typeof(T)</c> and a mapping
    /// exists precisely because no earlier step put a <c>TStepIn</c> there, so writing one
    /// back would invent a producer FLOWX1020 cannot see, and two mapped steps of the same
    /// type in one flow would overwrite each other's input. As a local, each mapped step
    /// has its own delegate and its own value, and neither is visible to anything else.
    /// </para>
    /// <para>
    /// Typed at the <c>TStepIn</c> C# inferred rather than at the capability's declared
    /// input, so the field's type is the one the author's lambda actually returns. FLOWX1029
    /// has already refused the case where the two are unrelated, which is what makes passing
    /// the first where the second is declared compile.
    /// </para>
    /// </remarks>
    private static void EmitStepInputs(SourceWriter writer, FlowModel flow)
    {
        var mapped = MappedSteps(flow);

        if (mapped.Count == 0)
        {
            return;
        }

        writer.Line("/// <summary>Step input mappings, built once at type initialisation.</summary>");
        writer.Line("/// <remarks>");
        writer.Line("/// Each is your <c>.Step&lt;TCapability, TStepIn&gt;(...)</c> expression, copied");
        writer.Line("/// verbatim. They obey the same determinism rule as a condition — context, flow");
        writer.Line("/// input and prior step results only — so that a replay hands the step the input");
        writer.Line("/// it had before. The result goes straight to the capability and is never written");
        writer.Line("/// into the state bag, so two mapped steps of the same type cannot collide.");
        writer.Line("/// </remarks>");
        writer.Line("private static class StepInputs");
        writer.OpenBrace();

        foreach (var step in mapped)
        {
            EmitLineDirective(writer, step.StepInputMapLocation);
            writer.Line(
                "public static readonly Func<FlowContext<" + flow.InputTypeName + ">, " +
                step.StepInputTypeName + "> Step" + step.Index + " = " + step.StepInputMap + ";");
            EmitLineDirectiveEnd(writer, step.StepInputMapLocation);
        }

        writer.CloseBrace();
        writer.Line();
    }

    /// <summary>
    /// Emits the names of the contract members marked <c>[Sensitive]</c>.
    /// </summary>
    /// <remarks>
    /// This is what turns the attribute from a fact recorded in the manifest into
    /// something a transport can act on. The endpoint uses it to strip matching keys out
    /// of a Problem Details body, which is the only path in this release that serialises
    /// anything a capability attached to an error.
    /// <para>
    /// Emitted even when empty, unlike the manifest's array: a caller passing
    /// <c>Flow.SensitiveMembers</c> must not have to know whether the flow has any, and a
    /// missing field would be a compile error rather than an empty guard.
    /// </para>
    /// </remarks>
    private static void EmitSensitiveMembers(SourceWriter writer, FlowModel flow)
    {
        var members = flow.SensitiveInputMembers
            .Concat(flow.SensitiveOutputMembers)
            .Distinct()
            .OrderBy(m => m, System.StringComparer.Ordinal)
            .ToList();

        writer.Line("/// <summary>Contract members declared <c>[Sensitive]</c>, ordinally sorted.</summary>");
        writer.Line("/// <remarks>");
        writer.Line("/// Pass to <c>MapFlow</c> so their values are stripped from an error response.");
        writer.Line("/// </remarks>");
        writer.Line(
            "public static readonly string[] SensitiveMembers = " +
            (members.Count == 0
                ? "System.Array.Empty<string>();"
                : "new[] { " + string.Join(", ", members.Select(m => "\"" + m + "\"")) + " };"));
        writer.Line();
    }

    /// <summary>Usings the generated file always carries, so copied ones are not repeated.</summary>
    private static readonly System.Collections.Generic.HashSet<string> EmittedUsings =
        new System.Collections.Generic.HashSet<string>(System.StringComparer.Ordinal)
        {
            "using System;",
            "using System.Threading;",
            "using System.Threading.Tasks;",
            "using FlowX;",
            "using FlowX.Runtime;",
        };

    /// <summary>
    /// Emits one <c>static readonly</c> delegate per <c>.When(...)</c> predicate.
    /// </summary>
    /// <remarks>
    /// A field, initialised once at type initialisation, for exactly the reason
    /// <c>Projection</c> is one: the engine's step loop must not allocate, and a lambda
    /// built at the call site would cost a delegate per branch per execution. Budget B2 is
    /// a hard zero, so a conditional flow would have failed it on the first commit.
    /// <para>
    /// The predicate is the author's own expression, copied verbatim inside a
    /// <c>#line</c> pair, so a breakpoint on the condition lands on the condition they
    /// wrote and a wrong-branch bug is debuggable rather than archaeological.
    /// </para>
    /// </remarks>
    private static void EmitConditions(SourceWriter writer, FlowModel flow)
    {
        var conditions = flow.AllSteps.Where(s => s.Kind == StepKindModel.Condition).ToList();

        if (conditions.Count == 0)
        {
            return;
        }

        writer.Line("/// <summary>Branch predicates, built once at type initialisation.</summary>");
        writer.Line("/// <remarks>");
        writer.Line("/// Each is your <c>.When(...)</c> expression, copied verbatim. They are pure and");
        writer.Line("/// synchronous by design: a condition may read only the context, the flow input");
        writer.Line("/// and prior step results, so that a replay takes the branch it took before.");
        writer.Line("/// </remarks>");
        writer.Line("private static class Conditions");
        writer.OpenBrace();

        foreach (var condition in conditions.OrderBy(c => c.Index))
        {
            EmitLineDirective(writer, condition.PredicateLocation);
            writer.Line(
                "public static readonly Func<FlowContext<" + flow.InputTypeName + ">, bool> Step" +
                condition.Index + " = " + condition.Predicate + ";");
            EmitLineDirectiveEnd(writer, condition.PredicateLocation);
        }

        writer.CloseBrace();
        writer.Line();
    }

    /// <summary>
    /// Emits one <c>static readonly</c> delegate per <c>.Switch(...)</c> selector.
    /// </summary>
    /// <remarks>
    /// A field, for the same reason the predicates are: budget B2 is a hard zero, and a
    /// lambda built at the switch would cost a delegate per execution. Typed at the value
    /// the selector actually produces, so <c>Select</c> below can compare against it
    /// without boxing.
    /// </remarks>
    private static void EmitSelectors(SourceWriter writer, FlowModel flow)
    {
        var switches = Switches(flow);

        if (switches.Count == 0)
        {
            return;
        }

        writer.Line("/// <summary>Switch selectors, built once at type initialisation.</summary>");
        writer.Line("/// <remarks>");
        writer.Line("/// Each is your <c>.Switch(...)</c> expression, copied verbatim. They obey the same");
        writer.Line("/// determinism rule as a condition — context, flow input and prior step results");
        writer.Line("/// only — so that a replay selects the case it selected before.");
        writer.Line("/// </remarks>");
        writer.Line("private static class Selectors");
        writer.OpenBrace();

        foreach (var step in switches)
        {
            EmitLineDirective(writer, step.SelectorLocation);
            writer.Line(
                "public static readonly Func<FlowContext<" + flow.InputTypeName + ">, " +
                step.SelectorTypeName + "> Step" + step.Index + " = " + step.Selector + ";");
            EmitLineDirectiveEnd(writer, step.SelectorLocation);
        }

        writer.CloseBrace();
        writer.Line();
    }

    /// <summary>The flow's value branches, ascending by flat index.</summary>
    private static System.Collections.Generic.List<StepModel> Switches(FlowModel flow) => flow.AllSteps
        .Where(s => s.Kind == StepKindModel.Switch)
        .OrderBy(s => s.Index)
        .ToList();

    /// <summary>The flow's iterations, ascending by flat index.</summary>
    private static System.Collections.Generic.List<StepModel> Iterations(FlowModel flow) => flow.AllSteps
        .Where(s => s.Kind == StepKindModel.ForEach)
        .OrderBy(s => s.Index)
        .ToList();

    /// <summary>
    /// Emits one <c>static readonly</c> delegate per <c>.ForEach(...)</c> collection
    /// selector.
    /// </summary>
    /// <remarks>
    /// A field, for the reason the predicates and the switch selectors are: it is built
    /// once at type initialisation rather than once per execution. It matters slightly less
    /// here — a loop is already allowed to allocate — but a delegate per loop per execution
    /// would be an allocation that scales with traffic to save nothing, and the emitted
    /// shape being the same as the other two is worth more than the byte.
    /// <para>
    /// Typed at <c>IReadOnlyList&lt;TItem&gt;</c>, not <c>IEnumerable&lt;TItem&gt;</c>: the
    /// engine reads the count once, before the first element, and that count is what bounds
    /// the loop. A sequence with no count could iterate forever inside a step loop that has
    /// no iteration cap by design.
    /// </para>
    /// </remarks>
    private static void EmitIterations(SourceWriter writer, FlowModel flow)
    {
        var iterations = Iterations(flow);

        if (iterations.Count == 0)
        {
            return;
        }

        writer.Line("/// <summary>Iteration selectors, built once at type initialisation.</summary>");
        writer.Line("/// <remarks>");
        writer.Line("/// Each is your <c>.ForEach(...)</c> expression, copied verbatim. They obey the same");
        writer.Line("/// determinism rule as a condition — context, flow input and prior step results");
        writer.Line("/// only — so that a replay walks the collection it walked before.");
        writer.Line("/// </remarks>");
        writer.Line("private static class Iterations");
        writer.OpenBrace();

        foreach (var step in iterations)
        {
            EmitLineDirective(writer, step.SelectorLocation);
            writer.Line(
                "public static readonly Func<FlowContext<" + flow.InputTypeName +
                ">, System.Collections.Generic.IReadOnlyList<" + step.ItemTypeName + ">> Step" +
                step.Index + " = " + step.Selector + ";");
            EmitLineDirectiveEnd(writer, step.SelectorLocation);
        }

        writer.CloseBrace();
        writer.Line();
    }

    /// <summary>The flow's sub-flow compositions, ascending by flat index.</summary>
    private static System.Collections.Generic.List<StepModel> SubFlows(FlowModel flow) => flow.AllSteps
        .Where(s => s.Kind == StepKindModel.SubFlow)
        .OrderBy(s => s.Index)
        .ToList();

    /// <summary>
    /// Emits one <c>static readonly</c> delegate per <c>.SubFlow(...)</c> input mapping.
    /// </summary>
    /// <remarks>
    /// A field, for the reason the predicates and the selectors are: built once at type
    /// initialisation rather than once per execution, so composing a flow does not cost a
    /// delegate allocation every time the parent runs.
    /// <para>
    /// Typed at the child's declared input contract, so the value the engine carries as an
    /// opaque handle is cast back to something the child's first step can bind to. A
    /// mapping typed at <c>object</c> would have boxed a record struct input and moved the
    /// error from build time to the child's first <c>ctx.Get&lt;T&gt;()</c>.
    /// </para>
    /// </remarks>
    private static void EmitSubFlowMaps(SourceWriter writer, FlowModel flow)
    {
        var subFlows = SubFlows(flow);

        if (subFlows.Count == 0)
        {
            return;
        }

        writer.Line("/// <summary>Sub-flow input mappings, built once at type initialisation.</summary>");
        writer.Line("/// <remarks>");
        writer.Line("/// Each is your <c>.SubFlow(...)</c> expression, copied verbatim. They obey the same");
        writer.Line("/// determinism rule as a condition — context, flow input and prior step results");
        writer.Line("/// only — and they run on this flow's thread before the child starts, so nothing");
        writer.Line("/// the child holds points back at this flow's pooled context.");
        writer.Line("/// </remarks>");
        writer.Line("private static class SubFlowInputs");
        writer.OpenBrace();

        foreach (var step in subFlows)
        {
            EmitLineDirective(writer, step.SubFlowMapLocation);
            writer.Line(
                "public static readonly Func<FlowContext<" + flow.InputTypeName + ">, " +
                step.SubFlowInputTypeName + "> Step" + step.Index + " = " + step.SubFlowMap + ";");
            EmitLineDirectiveEnd(writer, step.SubFlowMapLocation);
        }

        writer.CloseBrace();
        writer.Line();
    }

    /// <summary>The flow's terminal failures, ascending by flat index.</summary>
    private static System.Collections.Generic.List<StepModel> Failures(FlowModel flow) => flow.AllSteps
        .Where(s => s.Kind == StepKindModel.Fail)
        .OrderBy(s => s.Index)
        .ToList();

    /// <summary>
    /// Emits one <c>static readonly Error</c> per <c>.Fail(...)</c>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// A field, for the reason the predicates and the selectors are: it is built once at
    /// type initialisation, so rejecting a request costs no allocation at the moment the
    /// flow is already about to unwind. An <c>Error</c> is immutable, so one instance
    /// shared by every execution is not merely cheap but correct.
    /// </para>
    /// <para>
    /// <strong>This is where the error value lives, and the only place it lives.</strong>
    /// The compiled plan carries a <c>StepKind.Fail</c> node with no payload and the
    /// manifest carries <c>"kind": "Fail"</c>, because a message interpolating a customer's
    /// order number is a value and the manifest publishes structure. The expression is the
    /// author's own, copied verbatim inside a <c>#line</c> pair, so a factory that decorates
    /// the error with structured detail compiles exactly as written and a breakpoint lands
    /// on the line they wrote.
    /// </para>
    /// </remarks>
    private static void EmitFailures(SourceWriter writer, FlowModel flow)
    {
        var failures = Failures(flow);

        if (failures.Count == 0)
        {
            return;
        }

        writer.Line("/// <summary>Terminal errors, built once at type initialisation.</summary>");
        writer.Line("/// <remarks>");
        writer.Line("/// Each is your <c>.Fail(...)</c> expression, copied verbatim. Reaching one ends");
        writer.Line("/// the flow: the engine takes the failure path and the completed compensable");
        writer.Line("/// steps unwind in strict reverse, exactly as they would for a declined payment.");
        writer.Line("/// </remarks>");
        writer.Line("private static class Failures");
        writer.OpenBrace();

        foreach (var step in failures)
        {
            EmitLineDirective(writer, step.FailureLocation);
            writer.Line(
                "public static readonly Error Step" + step.Index + " = " + step.FailureExpression + ";");
            EmitLineDirectiveEnd(writer, step.FailureLocation);
        }

        writer.CloseBrace();
        writer.Line();
    }

    private static void EmitDescriptors(SourceWriter writer, FlowModel flow)
    {
        writer.Line("/// <summary>Capability descriptors, built once at type initialisation.</summary>");
        writer.Line("private static class Descriptors");
        writer.OpenBrace();

        foreach (var step in flow.AllSteps.Where(s => s.Kind == StepKindModel.Capability))
        {
            writer.Line(
                "public static readonly CapabilityDescriptor Step" + step.Index + " = " +
                DescriptorCall(step.CapabilityId!, step.CapabilityVersion!, step.IsIdempotent, step.SideEffects) + ";");

            if (step.IsCompensable)
            {
                writer.Line(
                    "public static readonly CapabilityDescriptor Step" + step.Index + "Compensation = " +
                    DescriptorCall(step.CompensationId!, step.CompensationVersion!, true, System.Array.Empty<string>()) + ";");
            }
        }

        writer.CloseBrace();
    }

    private static string DescriptorCall(string id, string version, bool idempotent, string[] sideEffects)
    {
        var effects = sideEffects.Length == 0
            ? string.Empty
            : ", " + string.Join(", ", sideEffects.Select(Quote));

        return "CapabilityDescriptor.Create(" + Quote(id) + ", " + Quote(version) + ", " +
               (idempotent ? "true" : "false") + effects + ")";
    }

    private static void EmitPlan(SourceWriter writer, FlowModel flow)
    {
        writer.Line("/// <summary>The compiled execution plan. Built once, shared by every invocation.</summary>");
        writer.Line("public static ExecutionPlan Plan { get; } = ExecutionPlan.Create(");
        writer.Line("    FlowDescriptor.Create(");
        writer.Line("        " + Quote(flow.FlowId) + ",");
        writer.Line("        " + Quote(flow.Version) + ",");
        writer.Line("        ExecutionProfile." + flow.Profile + ",");
        writer.Line("        " + DeadlineExpression(flow.Deadline) + "),");
        writer.Line("    StepGraph.Create(new StepNode[]");
        writer.Line("    {");

        EmitStepNodes(writer, flow.Steps);

        writer.Line("    }));");
    }

    /// <summary>
    /// Writes the step array, flattening conditionals into branch-and-jump form.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The layout is <c>branch · then… · jump · otherwise…</c>. The branch carries only
    /// its false target, because the <c>then</c> block starts at the very next index; the
    /// jump exists solely so a taken <c>then</c> block skips the alternative, and is
    /// omitted when there is no alternative to skip. Nested conditionals recurse, and
    /// their indices were already assigned in this same order during analysis — which is
    /// why the array comes out contiguous and <c>StepGraph.Create</c> accepts it.
    /// </para>
    /// <para>
    /// A switch is the same shape with more blocks:
    /// <c>switch · case₀… · jump · case₁… · jump · … · default…</c>. Each block is closed
    /// by a jump to the join, except the last non-empty one, which falls into the join
    /// anyway.
    /// </para>
    /// </remarks>
    private static void EmitStepNodes(SourceWriter writer, System.Collections.Generic.IReadOnlyList<StepModel> steps)
    {
        foreach (var step in steps)
        {
            switch (step.Kind)
            {
                case StepKindModel.Condition:
                    writer.Line("        StepNode.ForBranch(" + step.Index + ", " + step.FalseTarget + "),");
                    EmitStepNodes(writer, step.Then);

                    if (step.JumpIndex is int jump)
                    {
                        writer.Line("        StepNode.ForJump(" + jump + ", " + step.JoinIndex + "),");
                        EmitStepNodes(writer, step.Otherwise);
                    }

                    break;

                case StepKindModel.Switch:
                    writer.Line("        " + SwitchNodeExpression(step) + ",");

                    foreach (var arm in step.Cases)
                    {
                        EmitStepNodes(writer, arm.Steps);

                        if (arm.JumpIndex is int caseJump)
                        {
                            writer.Line("        StepNode.ForJump(" + caseJump + ", " + step.JoinIndex + "),");
                        }
                    }

                    EmitStepNodes(writer, step.Default);
                    break;

                case StepKindModel.Parallel:
                    writer.Line("        " + ParallelNodeExpression(step) + ",");

                    foreach (var branch in step.Branches)
                    {
                        EmitStepNodes(writer, branch.Steps);
                    }

                    break;

                case StepKindModel.ForEach:
                    // `foreach · body…`, and that is the whole layout: one block, starting
                    // at the very next index, with nothing after it to skip. The body
                    // appears once however many elements the collection turns out to hold.
                    writer.Line("        " + ForEachNodeExpression(step) + ",");
                    EmitStepNodes(writer, step.Body);
                    break;

                case StepKindModel.SubFlow:
                    // One node and nothing else. The child's steps are in the child's own
                    // generated plan, so there is no block here to recurse into — which is
                    // why a flow that composes a hundred-step child emits one line.
                    writer.Line("        " + SubFlowNodeExpression(step) + ",");
                    break;

                default:
                    writer.Line("        " + StepNodeExpression(step) + ",");
                    break;
            }
        }
    }

    private static string SwitchNodeExpression(StepModel step)
    {
        var targets = string.Join(
            ", ",
            step.Cases.Select(c => c.Target.ToString(CultureInfo.InvariantCulture)));

        return "StepNode.ForSwitch(" + step.Index + ", new[] { " + targets + " }, defaultTarget: " +
               step.DefaultTarget + ")";
    }

    /// <summary>
    /// Emits the fork node, with the author's <c>merge:</c> expression copied verbatim.
    /// </summary>
    /// <remarks>
    /// Verbatim rather than reconstructed from <c>MergeKindName</c>, so that
    /// <c>MergeStrategy.Quorum(RequiredChecks)</c> compiles into the plan as written and a
    /// strategy chosen through a constant on the flow keeps working. Reconstructing it
    /// would mean the generated plan disagreed with the source for every expression the
    /// name-reader could not recognise.
    /// </remarks>
    private static string ParallelNodeExpression(StepModel step)
    {
        var targets = string.Join(
            ", ",
            step.Branches
                .Where(b => b.Steps.Count > 0)
                .Select(b => b.Target.ToString(CultureInfo.InvariantCulture)));

        return "StepNode.ForParallel(" + step.Index + ", new[] { " + targets + " }, joinTarget: " +
               step.JoinIndex + ", merge: " + step.MergeExpression + ")";
    }

    /// <summary>
    /// Emits the loop node, with the author's <c>options:</c> expression copied verbatim.
    /// </summary>
    /// <remarks>
    /// Verbatim rather than reconstructed from the values, for the reason
    /// <see cref="ParallelNodeExpression"/> copies the merge: an author may write
    /// <c>new ForEachOptions { MaxDegreeOfParallelism = Concurrency }</c>, and a generator
    /// that rebuilt the object literal would disagree with the source for every expression
    /// it could not fold. The runtime clamps the bound; the generator does not evaluate it.
    /// </remarks>
    private static string ForEachNodeExpression(StepModel step) =>
        "StepNode.ForEach(" + step.Index + ", joinTarget: " + step.JoinIndex +
        ", options: " + step.OptionsExpression + ")";

    /// <summary>Emits the composition node: which flow, and how it relates to this one.</summary>
    /// <remarks>
    /// The child's <em>id</em> reaches the plan, not its plan object. A node holding another
    /// plan would make two flows' type initialisers depend on each other, which is a cycle
    /// the CLR resolves by handing one of them a null — and it would put the child's whole
    /// graph inside the parent's static state for no gain, since the thing the engine
    /// actually needs at run time comes from the dispatcher.
    /// </remarks>
    private static string SubFlowNodeExpression(StepModel step) =>
        "StepNode.ForSubFlow(" + step.Index + ", " + Quote(step.SubFlowId!) +
        ", SubFlowMode." + step.SubFlowMode + ")";

    private static string StepNodeExpression(StepModel step)
    {
        switch (step.Kind)
        {
            case StepKindModel.Emit:
                return "StepNode.ForEmit(" + step.Index + ", " + Quote(step.EventType!) + ")";

            case StepKindModel.AwaitSignal:
                // This arm used to write the author's signal and a hard-coded one-hour
                // timeout, whatever duration they declared — so a flow written to wait seven
                // days published a plan and a manifest saying one hour. The model carries no
                // timeout to write instead: that field arrives with WP-63, which is also
                // when the step gets a meaning. Until then FLOWX1031 is an error on every
                // AwaitSignal, so no model containing one is ever emitted, and this arm
                // states the invariant rather than inventing a value to satisfy it.
                throw new System.InvalidOperationException(
                    "AwaitSignal reaches no execution plan in this release: FLOWX1031 refuses " +
                    "the flow, because the compiler has no timeout to emit but the one the " +
                    "author wrote and no way to carry it. See docs/diagnostics/FLOWX1031.md.");

            case StepKindModel.Fail:
                // No payload. The error is in `Failures` above, which is where a business
                // value belongs — the plan says only that the flow ends here.
                return "StepNode.ForFail(" + step.Index + ")";

            default:
                var compensation = step.IsCompensable
                    ? ", Descriptors.Step" + step.Index + "Compensation"
                    : string.Empty;

                return "StepNode.ForCapability(" + step.Index + ", Descriptors.Step" + step.Index +
                       compensation + ")";
        }
    }

    private static string DeadlineExpression(string? iso8601)
    {
        // A flow without an explicit deadline gets thirty seconds. Stated here rather
        // than defaulted silently in the runtime: an unbounded flow is not a default
        // anyone would choose deliberately.
        return iso8601 == null
            ? "TimeSpan.FromSeconds(30)"
            : "System.Xml.XmlConvert.ToTimeSpan(" + Quote(iso8601) + ")";
    }

    private static void EmitDispatcher(
        SourceWriter writer, FlowModel flow, IReadOnlyList<StagedEvent> staged)
    {
        writer.Line("/// <summary>Invokes the capability behind each step index.</summary>");
        writer.Line("/// <remarks>");
        writer.Line("/// A switch, not a lookup. The engine's loop cannot know each step's types;");
        writer.Line("/// this class does, which is why nothing here is boxed and no reflection runs.");
        writer.Line("/// </remarks>");
        writer.Line("public sealed class Dispatcher : IStepDispatcher");
        writer.OpenBrace();

        EmitDispatcherFields(writer, flow);
        writer.Line();
        EmitDispatcherConstructor(writer, flow);
        writer.Line();
        EmitDispatcherExecute(writer, flow);
        writer.Line();
        EmitDispatcherCompensate(writer, flow);
        writer.Line();
        EmitDispatcherEvaluate(writer, flow);
        writer.Line();
        EmitDispatcherSelect(writer, flow);
        writer.Line();
        EmitDispatcherIteration(writer, flow);
        writer.Line();
        EmitDispatcherSubFlow(writer, flow);

        if (staged.Count > 0)
        {
            writer.Line();
            EmitDispatcherDescribe(writer, staged);
        }

        writer.CloseBrace();
    }

    /// <summary>
    /// Emits <c>BeginSubFlow</c> and <c>EnterSubFlow</c>: which flow to compose, and the
    /// input to seed into it.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The pair is the whole of what the engine cannot do for itself, and it is deliberately
    /// the <em>only</em> thing generated here. Renting the child's context, deriving its
    /// deadline from this flow's, running its graph and unwinding its compensation are the
    /// engine's job and are identical for every flow; emitting them per composing flow would
    /// have put four subtle behaviours into generated source, where a mistake is hardest to
    /// see and impossible to fix without a rebuild.
    /// </para>
    /// <para>
    /// <c>EnterSubFlow</c> writes into the <em>child's</em> context, which is a different
    /// object from the one every other method here receives. That is what makes a detached
    /// child safe: the two contexts never meet, so a child outliving its parent cannot read
    /// a context that has since been reset and rented to another tenant's flow.
    /// </para>
    /// </remarks>
    private static void EmitDispatcherSubFlow(SourceWriter writer, FlowModel flow)
    {
        var subFlows = SubFlows(flow);

        writer.Line("/// <inheritdoc />");
        writer.Line("public SubFlowSource BeginSubFlow(int stepIndex, FlowContext ctx)");
        writer.OpenBrace();

        if (subFlows.Count == 0)
        {
            EmitNoSubFlow(writer, "compose");
            writer.CloseBrace();
            writer.Line();
            EmitDispatcherEnterSubFlow(writer, subFlows);
            return;
        }

        writer.Line("switch (stepIndex)");
        writer.OpenBrace();

        foreach (var step in subFlows)
        {
            writer.Line("case " + step.Index + ":");
            writer.OpenBrace();
            writer.Line(
                "return new SubFlowSource(" + step.SubFlowTypeName + ".Plan, " +
                SubFlowFieldName(step.SubFlowTypeName!) + ", SubFlowInputs.Step" + step.Index +
                "(Typed(ctx)));");
            writer.CloseBrace();
        }

        EmitSubFlowDefaultCase(writer);

        writer.CloseBrace();
        writer.CloseBrace();
        writer.Line();

        EmitDispatcherEnterSubFlow(writer, subFlows);
    }

    private static void EmitDispatcherEnterSubFlow(
        SourceWriter writer, System.Collections.Generic.List<StepModel> subFlows)
    {
        writer.Line("/// <inheritdoc />");
        writer.Line("public void EnterSubFlow(int stepIndex, in SubFlowSource source, FlowContext child)");
        writer.OpenBrace();

        if (subFlows.Count == 0)
        {
            EmitNoSubFlow(writer, "seed");
            writer.CloseBrace();
            return;
        }

        writer.Line("switch (stepIndex)");
        writer.OpenBrace();

        foreach (var step in subFlows)
        {
            writer.Line("case " + step.Index + ":");
            writer.OpenBrace();
            writer.Line("// The child's own context, never this flow's. Seeding it here is");
            writer.Line("// what lets the child's first step bind to its input by type.");
            writer.Line("child.Set((" + step.SubFlowInputTypeName + ")source.Input!);");
            writer.Line("return;");
            writer.CloseBrace();
        }

        EmitSubFlowDefaultCase(writer);

        writer.CloseBrace();
        writer.CloseBrace();
    }

    private static void EmitNoSubFlow(SourceWriter writer, string verb)
    {
        writer.Line("throw new ArgumentOutOfRangeException(");
        writer.Line("    nameof(stepIndex),");
        writer.Line("    stepIndex,");
        writer.Line("    \"This flow composes no sub-flow, so the engine never asks it to " + verb + " \" +");
        writer.Line("    \"one. Reaching this means the plan and this dispatcher came from \" +");
        writer.Line("    \"different builds.\");");
    }

    private static void EmitSubFlowDefaultCase(SourceWriter writer)
    {
        writer.Line("default:");
        writer.OpenBrace();
        writer.Line("throw new ArgumentOutOfRangeException(");
        writer.Line("    nameof(stepIndex),");
        writer.Line("    stepIndex,");
        writer.Line("    \"Step index does not name a sub-flow in the compiled plan. The plan \" +");
        writer.Line("    \"and this dispatcher are generated together, so this means they came \" +");
        writer.Line("    \"from different builds.\");");
        writer.CloseBrace();
    }

    /// <summary>
    /// Emits <c>BeginIteration</c> and <c>EnterIteration</c>: the collection each loop
    /// walks, and the element each pass over its body is for.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The pair is the whole of what the engine cannot do for itself. It has no idea what a
    /// <c>ValidatedOrder.Lines</c> is, so it asks for a count and an opaque handle, then
    /// hands the handle back once per element and gets a context in return. Everything typed
    /// happens here, in generated code, which is the same division that keeps capabilities
    /// reflection-free.
    /// </para>
    /// <para>
    /// <c>EnterIteration</c> is one indexed read and one small object. It is deliberately
    /// not a <c>foreach</c> over the collection: the concurrent path runs several elements
    /// at once and would have to share a single enumerator, which no
    /// <c>IEnumerator&lt;T&gt;</c> supports.
    /// </para>
    /// </remarks>
    private static void EmitDispatcherIteration(SourceWriter writer, FlowModel flow)
    {
        var iterations = Iterations(flow);

        writer.Line("/// <inheritdoc />");
        writer.Line("public IterationSource BeginIteration(int stepIndex, FlowContext ctx)");
        writer.OpenBrace();

        if (iterations.Count == 0)
        {
            writer.Line("throw new ArgumentOutOfRangeException(");
            writer.Line("    nameof(stepIndex),");
            writer.Line("    stepIndex,");
            writer.Line("    \"This flow declares no iteration, so the engine never asks it for a \" +");
            writer.Line("    \"collection. Reaching this means the plan and this dispatcher came from \" +");
            writer.Line("    \"different builds.\");");
            writer.CloseBrace();
            writer.Line();
            EmitDispatcherEnterIteration(writer, iterations);
            return;
        }

        writer.Line("switch (stepIndex)");
        writer.OpenBrace();

        foreach (var step in iterations)
        {
            writer.Line("case " + step.Index + ":");
            writer.OpenBrace();
            writer.Line("var items = Iterations.Step" + step.Index + "(Typed(ctx));");
            writer.Line("return new IterationSource(items, items.Count);");
            writer.CloseBrace();
        }

        EmitIterationDefaultCase(writer);

        writer.CloseBrace();
        writer.CloseBrace();
        writer.Line();

        EmitDispatcherEnterIteration(writer, iterations);
    }

    private static void EmitDispatcherEnterIteration(
        SourceWriter writer, System.Collections.Generic.List<StepModel> iterations)
    {
        writer.Line("/// <inheritdoc />");
        writer.Line(
            "public FlowContext EnterIteration(int stepIndex, in IterationSource source, " +
            "int iteration, FlowContext ctx)");
        writer.OpenBrace();

        if (iterations.Count == 0)
        {
            writer.Line("throw new ArgumentOutOfRangeException(");
            writer.Line("    nameof(stepIndex),");
            writer.Line("    stepIndex,");
            writer.Line("    \"This flow declares no iteration, so the engine never asks it for an \" +");
            writer.Line("    \"element. Reaching this means the plan and this dispatcher came from \" +");
            writer.Line("    \"different builds.\");");
            writer.CloseBrace();
            return;
        }

        writer.Line("switch (stepIndex)");
        writer.OpenBrace();

        foreach (var step in iterations)
        {
            writer.Line("case " + step.Index + ":");
            writer.OpenBrace();
            writer.Line(
                "var items = (System.Collections.Generic.IReadOnlyList<" + step.ItemTypeName +
                ">)source.Items!;");
            writer.Line();
            writer.Line("// The element shadows the flow's state bag on its own type, for");
            writer.Line("// exactly this pass over the body. Writes still go to the bag.");
            writer.Line("return IterationScope.For(ctx, items[iteration]);");
            writer.CloseBrace();
        }

        EmitIterationDefaultCase(writer);

        writer.CloseBrace();
        writer.CloseBrace();
    }

    private static void EmitIterationDefaultCase(SourceWriter writer)
    {
        writer.Line("default:");
        writer.OpenBrace();
        writer.Line("throw new ArgumentOutOfRangeException(");
        writer.Line("    nameof(stepIndex),");
        writer.Line("    stepIndex,");
        writer.Line("    \"Step index does not name an iteration in the compiled plan. The plan \" +");
        writer.Line("    \"and this dispatcher are generated together, so this means they came \" +");
        writer.Line("    \"from different builds.\");");
        writer.CloseBrace();
    }

    private static void EmitDispatcherFields(SourceWriter writer, FlowModel flow)
    {
        foreach (var capability in flow.ReferencedCapabilities)
        {
            writer.Line("private readonly " + capability + " " + FieldName(capability) + ";");
        }

        foreach (var composed in flow.ComposedFlows)
        {
            writer.Line(
                "private readonly " + composed + ".Dispatcher " + SubFlowFieldName(composed) + ";");
        }
    }

    /// <summary>
    /// Emits the dispatcher's constructor: one parameter per capability, then one per
    /// composed flow.
    /// </summary>
    /// <remarks>
    /// <strong>A child's dispatcher is injected, not constructed here.</strong> Building one
    /// would mean this flow had to know the child's capabilities, which is exactly the
    /// coupling composition exists to avoid — and it would build a fresh one per parent
    /// rather than sharing the container's. Injection also means a child in another assembly
    /// costs this flow nothing but a type reference.
    /// </remarks>
    private static void EmitDispatcherConstructor(SourceWriter writer, FlowModel flow)
    {
        var parameters = string.Join(
            ", ",
            flow.ReferencedCapabilities.Select(c => c + " " + ParameterName(c))
                .Concat(flow.ComposedFlows.Select(f => f + ".Dispatcher " + SubFlowParameterName(f))));

        writer.Line("/// <summary>Capabilities and composed flows are injected, never resolved by reflection.</summary>");
        writer.Line("public Dispatcher(" + parameters + ")");
        writer.OpenBrace();

        foreach (var capability in flow.ReferencedCapabilities)
        {
            writer.Line(FieldName(capability) + " = " + ParameterName(capability) + ";");
        }

        foreach (var composed in flow.ComposedFlows)
        {
            writer.Line(SubFlowFieldName(composed) + " = " + SubFlowParameterName(composed) + ";");
        }

        writer.CloseBrace();
    }

    /// <summary>
    /// The field holding one composed flow's dispatcher.
    /// </summary>
    /// <remarks>
    /// Named from the <em>flow</em> and not from the nested <c>Dispatcher</c> type, because
    /// every child's dispatcher is called <c>Dispatcher</c> — deriving the name the way a
    /// capability's is derived would give two composed flows the same field.
    /// </remarks>
    private static string SubFlowFieldName(string flowTypeName) => "_" + SubFlowParameterName(flowTypeName);

    private static string SubFlowParameterName(string flowTypeName) =>
        ParameterName(flowTypeName) + "Dispatcher";

    private static void EmitDispatcherExecute(SourceWriter writer, FlowModel flow)
    {
        writer.Line("/// <inheritdoc />");
        writer.Line("public async ValueTask<StepOutcome> ExecuteAsync(int stepIndex, FlowContext ctx, CancellationToken ct)");
        writer.OpenBrace();
        writer.Line("switch (stepIndex)");
        writer.OpenBrace();

        // Conditions, switches, forks, loops and sub-flows have no case: the engine reaches
        // a condition through Evaluate, a switch through Select, a loop through
        // BeginIteration and a composition through BeginSubFlow, and it handles a fork, a
        // loop and a child flow entirely itself — the blocks' own steps get cases, the
        // branching node does not, and a child's steps are the child's dispatcher's
        // business. A case here would be dead code in the file the header promises is
        // readable.
        foreach (var step in flow.AllSteps
            .Where(s => s.Kind is not (StepKindModel.Condition or StepKindModel.Switch
                or StepKindModel.Parallel or StepKindModel.ForEach or StepKindModel.SubFlow))
            .OrderBy(s => s.Index))
        {
            writer.Line("case " + step.Index + ":");
            writer.OpenBrace();

            if (step.Kind == StepKindModel.Capability)
            {
                EmitCapabilityInvocation(
                    writer,
                    FieldName(step.CapabilityTypeName!),
                    InputExpression(step),
                    step.CapabilityOutput,
                    step.Location);
            }
            else if (step.Kind == StepKindModel.Fail)
            {
                // `.Fail(...)` invokes nothing; it hands the engine the error your flow
                // declared. Delivered through the same call a declined payment comes back
                // on, so the engine treats the two identically — the failure path, and the
                // unwind of everything compensable that completed before this point.
                writer.Line("return StepOutcome.Failed(Failures.Step" + step.Index + ");");
            }
            else
            {
                // Emit and AwaitSignal have no capability to call; the engine and the
                // event plugin handle them. Returning success keeps the switch total.
                writer.Line("return StepOutcome.Success;");
            }

            writer.CloseBrace();
        }

        writer.Line("default:");
        writer.OpenBrace();
        writer.Line("throw new ArgumentOutOfRangeException(");
        writer.Line("    nameof(stepIndex),");
        writer.Line("    stepIndex,");
        writer.Line("    \"Step index is outside the compiled plan. The plan and this dispatcher \" +");
        writer.Line("    \"are generated together, so this means they came from different builds.\");");
        writer.CloseBrace();

        writer.CloseBrace();
        writer.CloseBrace();
    }

    /// <summary>
    /// How one step gets its input: out of the state bag by type, or from the mapping the
    /// author wrote.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Step inputs are bound by type out of the flow's state bag. The flow's own input is
    /// seeded there by the engine; every later step reads what an earlier one returned.
    /// That is what lets a chain of differently-typed steps run through an engine that
    /// knows none of the types.
    /// </para>
    /// <para>
    /// <strong>A mapped step short-circuits that lookup entirely</strong> — it does not
    /// read the bag and does not write to it. The mapping runs on this thread, immediately
    /// before the call, and its result is an argument and nothing more. See
    /// <see cref="EmitStepInputs"/> for why the value deliberately does not live in the
    /// bag.
    /// </para>
    /// </remarks>
    private static string InputExpression(StepModel step) =>
        step.HasInputMapping
            ? "StepInputs.Step" + step.Index + "(Typed(ctx))"
            : step.CapabilityInput is null
                ? "ctx"
                : "ctx.Get<" + step.CapabilityInput + ">()";

    private static void EmitCapabilityInvocation(
        SourceWriter writer,
        string field,
        string input,
        string? outputType,
        string? location)
    {
        EmitLineDirective(writer, location);
        writer.Line("var result = await " + field + ".ExecuteAsync(" + input + ", ctx, ct).ConfigureAwait(false);");
        EmitLineDirectiveEnd(writer, location);

        writer.Line("if (!result.IsSuccess)");
        writer.OpenBrace();
        writer.Line("return StepOutcome.Failed(result.Error);");
        writer.CloseBrace();
        writer.Line();

        if (outputType is not null)
        {
            // Stored so the next step can bind to it.
            writer.Line("ctx.Set(result.Value);");
        }

        writer.Line("return StepOutcome.Success;");
    }

    private static void EmitDispatcherCompensate(SourceWriter writer, FlowModel flow)
    {
        writer.Line("/// <inheritdoc />");
        writer.Line("public async ValueTask<StepOutcome> CompensateAsync(int stepIndex, FlowContext ctx, CancellationToken ct)");
        writer.OpenBrace();
        writer.Line("switch (stepIndex)");
        writer.OpenBrace();

        foreach (var step in flow.AllSteps.Where(s => s.IsCompensable).OrderBy(s => s.Index))
        {
            writer.Line("case " + step.Index + ":");
            writer.OpenBrace();

            // The compensation binds to the step's own input — the thing it has to undo.
            // For a mapped step that means re-running the mapping rather than reading a
            // bag entry that was never written. Re-running is sound for the same reason
            // reading the bag is: the mapping is pure and deterministic (FLOWX1011), and
            // both routes see whatever the context holds at unwind time — a later step
            // that produced the same type again would move the value under an unmapped
            // compensation exactly as it moves it under this one.
            EmitCapabilityInvocation(
                writer,
                FieldName(step.CompensationTypeName!),
                InputExpression(step),
                outputType: null,
                step.Location);

            writer.CloseBrace();
        }

        writer.Line("default:");
        writer.OpenBrace();
        writer.Line("// The engine only compensates steps that declared one, so reaching");
        writer.Line("// here means the plan and this dispatcher disagree.");
        writer.Line("return StepOutcome.Success;");
        writer.CloseBrace();

        writer.CloseBrace();
        writer.CloseBrace();
    }

    private static void EmitDispatcherEvaluate(SourceWriter writer, FlowModel flow)
    {
        var conditions = flow.AllSteps
            .Where(s => s.Kind == StepKindModel.Condition)
            .OrderBy(s => s.Index)
            .ToList();

        writer.Line("/// <inheritdoc />");
        writer.Line("public bool Evaluate(int stepIndex, FlowContext ctx)");
        writer.OpenBrace();

        if (conditions.Count == 0)
        {
            // No switch at all rather than one with only a default. A flow with no
            // conditional has no branch for the engine to ask about, and an empty switch
            // reads like an oversight.
            writer.Line("throw new ArgumentOutOfRangeException(");
            writer.Line("    nameof(stepIndex),");
            writer.Line("    stepIndex,");
            writer.Line("    \"This flow declares no conditional, so the engine never asks it to \" +");
            writer.Line("    \"evaluate one. Reaching this means the plan and this dispatcher came \" +");
            writer.Line("    \"from different builds.\");");
            writer.CloseBrace();
            return;
        }

        writer.Line("switch (stepIndex)");
        writer.OpenBrace();

        foreach (var condition in conditions)
        {
            writer.Line("case " + condition.Index + ":");
            writer.OpenBrace();
            writer.Line("return Conditions.Step" + condition.Index + "(Typed(ctx));");
            writer.CloseBrace();
        }

        writer.Line("default:");
        writer.OpenBrace();
        writer.Line("throw new ArgumentOutOfRangeException(");
        writer.Line("    nameof(stepIndex),");
        writer.Line("    stepIndex,");
        writer.Line("    \"Step index does not name a branch in the compiled plan. The plan and \" +");
        writer.Line("    \"this dispatcher are generated together, so this means they came from \" +");
        writer.Line("    \"different builds.\");");
        writer.CloseBrace();

        writer.CloseBrace();
        writer.CloseBrace();
    }

    /// <summary>
    /// Emits <c>Select</c>: which case of each switch matched, by step index.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The selector runs <em>once</em> and the arms are then tested against the value it
    /// produced. Compiling a switch into a chain of equality predicates would have read
    /// the selector once per arm, which is wrong for a reader and wasteful for a machine.
    /// </para>
    /// <para>
    /// The comparison is <c>EqualityComparer&lt;T&gt;.Default.Equals</c> rather than a C#
    /// <c>switch</c> statement, because a case value is an arbitrary expression and a
    /// <c>case</c> label demands a compile-time constant — <c>.Case(Channel.Retail, …)</c>
    /// would compile and <c>.Case(_defaults.Channel, …)</c> would not. The comparer is a
    /// cached static at the real type, so an <c>enum</c>, an <c>int</c> and a
    /// <c>string</c> all compare without boxing and the arm costs nothing to take.
    /// </para>
    /// </remarks>
    private static void EmitDispatcherSelect(SourceWriter writer, FlowModel flow)
    {
        var switches = Switches(flow);

        writer.Line("/// <inheritdoc />");
        writer.Line("public int Select(int stepIndex, FlowContext ctx)");
        writer.OpenBrace();

        if (switches.Count == 0)
        {
            writer.Line("throw new ArgumentOutOfRangeException(");
            writer.Line("    nameof(stepIndex),");
            writer.Line("    stepIndex,");
            writer.Line("    \"This flow declares no switch, so the engine never asks it to select a \" +");
            writer.Line("    \"case. Reaching this means the plan and this dispatcher came from \" +");
            writer.Line("    \"different builds.\");");
            writer.CloseBrace();
            return;
        }

        writer.Line("switch (stepIndex)");
        writer.OpenBrace();

        foreach (var step in switches)
        {
            writer.Line("case " + step.Index + ":");
            writer.OpenBrace();
            writer.Line("var value = Selectors.Step" + step.Index + "(Typed(ctx));");

            for (var arm = 0; arm < step.Cases.Count; arm++)
            {
                writer.Line();
                EmitLineDirective(writer, step.Cases[arm].ValueLocation);
                writer.Line(
                    "if (System.Collections.Generic.EqualityComparer<" + step.SelectorTypeName +
                    ">.Default.Equals(value, " + step.Cases[arm].Value + "))");
                writer.OpenBrace();
                writer.Line("return " + arm.ToString(CultureInfo.InvariantCulture) + ";");
                writer.CloseBrace();
                EmitLineDirectiveEnd(writer, step.Cases[arm].ValueLocation);
            }

            writer.Line();
            writer.Line("// No case matched. The engine takes the switch's default target,");
            writer.Line("// which is the `Default` block when there is one and the join when");
            writer.Line("// there is not — a value nothing matched simply continues.");
            writer.Line("return -1;");
            writer.CloseBrace();
        }

        writer.Line("default:");
        writer.OpenBrace();
        writer.Line("throw new ArgumentOutOfRangeException(");
        writer.Line("    nameof(stepIndex),");
        writer.Line("    stepIndex,");
        writer.Line("    \"Step index does not name a switch in the compiled plan. The plan and \" +");
        writer.Line("    \"this dispatcher are generated together, so this means they came from \" +");
        writer.Line("    \"different builds.\");");
        writer.CloseBrace();

        writer.CloseBrace();
        writer.CloseBrace();
    }

    private static void EmitLineDirective(SourceWriter writer, string? location)
    {
        if (location == null)
        {
            return;
        }

        var separator = location.LastIndexOf(':');

        if (separator <= 0)
        {
            return;
        }

        var file = location.Substring(0, separator);
        var line = location.Substring(separator + 1);

        // Maps the emitted call back to the .Step<T>() that declared it, so a
        // breakpoint and a stack trace both land in the developer's own file.
        writer.Line("#line " + line + " \"" + file.Replace("\\", "\\\\") + "\"");
    }

    private static void EmitLineDirectiveEnd(SourceWriter writer, string? location)
    {
        if (location != null)
        {
            writer.Line("#line default");
        }
    }

    private static string FieldName(string fullTypeName) => "_" + ParameterName(fullTypeName);

    private static string ParameterName(string fullTypeName)
    {
        var simple = fullTypeName;
        var lastDot = simple.LastIndexOf('.');

        if (lastDot >= 0)
        {
            simple = simple.Substring(lastDot + 1);
        }

        return simple.Length == 0
            ? "capability"
            : char.ToLowerInvariant(simple[0]) + simple.Substring(1);
    }

    private static string Quote(string value) =>
        "\"" + value.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
}
