using System.Globalization;
using System.Linq;
using FlowX.Compiler.Model;

namespace FlowX.Compiler.Emit;

/// <summary>
/// Turns a <see cref="FlowModel"/> into the C# a flow needs at run time: its
/// compiled <c>ExecutionPlan</c> and its <c>IStepDispatcher</c>.
/// </summary>
/// <remarks>
/// <para>
/// Pure. Takes a model, returns a string, touches nothing else — which is what
/// makes every emitted shape testable by comparing text, with no compilation and
/// no Roslyn host. That is the second half of the R1 mitigation.
/// </para>
/// <para>
/// The emitted dispatcher is the reason the engine can stay type-agnostic. It holds
/// each step's typed input and output in its own fields and switches on the step
/// index, so nothing is boxed and the engine never learns what a
/// <c>ReserveRequest</c> is. See <c>IStepDispatcher</c> for why that split exists.
/// </para>
/// </remarks>
public static class FlowEmitter
{
    /// <summary>The header every generated file carries.</summary>
    public const string Header =
        "// <auto-generated>\n" +
        "//     Generated by FlowX.Compiler from the Define method of this flow.\n" +
        "//\n" +
        "//     This file is real C#, on disk, with line directives back to your source.\n" +
        "//     Set a breakpoint in it. If it is hard to read, that is a bug in the\n" +
        "//     generator, not something you are supposed to put up with.\n" +
        "// </auto-generated>\n";

    /// <summary>The file name this model's generated source should be written to.</summary>
    public static string FileNameFor(FlowModel flow)
    {
        if (flow is null)
        {
            throw new System.ArgumentNullException(nameof(flow));
        }

        return flow.FullTypeName + ".Flow.g.cs";
    }

    /// <summary>Emits the plan and dispatcher for one flow.</summary>
    public static string Emit(FlowModel flow)
    {
        if (flow is null)
        {
            throw new System.ArgumentNullException(nameof(flow));
        }

        var writer = new SourceWriter();

        writer.Line(Header.TrimEnd('\n'));
        writer.Line("#nullable enable");
        writer.Line();
        writer.Line("using System;");
        writer.Line("using System.Threading;");
        writer.Line("using System.Threading.Tasks;");
        writer.Line("using FlowX;");
        writer.Line("using FlowX.Runtime;");
        writer.Line();

        var hasNamespace = !string.IsNullOrEmpty(flow.ContainingNamespace);

        if (hasNamespace)
        {
            writer.Line("namespace " + flow.ContainingNamespace);
            writer.OpenBrace();
        }

        EmitFlowPartial(writer, flow);

        if (hasNamespace)
        {
            writer.CloseBrace();
        }

        return writer.ToString();
    }

    private static void EmitFlowPartial(SourceWriter writer, FlowModel flow)
    {
        writer.Line("/// <summary>Compiled plan and dispatcher for <c>" + flow.FlowId + "</c>.</summary>");
        writer.Line("partial class " + flow.TypeName);
        writer.OpenBrace();

        EmitDescriptors(writer, flow);
        writer.Line();
        EmitPlan(writer, flow);
        writer.Line();
        EmitDispatcher(writer, flow);

        writer.CloseBrace();
    }

    private static void EmitDescriptors(SourceWriter writer, FlowModel flow)
    {
        writer.Line("/// <summary>Capability descriptors, built once at type initialisation.</summary>");
        writer.Line("private static class Descriptors");
        writer.OpenBrace();

        foreach (var step in flow.Steps.Where(s => s.Kind == StepKindModel.Capability))
        {
            writer.Line(
                "public static readonly CapabilityDescriptor Step" + step.Index + " = " +
                DescriptorCall(step.CapabilityId!, step.CapabilityVersion!, step.IsIdempotent, step.SideEffects) + ";");

            if (step.IsCompensable)
            {
                writer.Line(
                    "public static readonly CapabilityDescriptor Step" + step.Index + "Compensation = " +
                    DescriptorCall(step.CompensationId!, step.CompensationVersion!, true, System.Array.Empty<string>()) + ";");
            }
        }

        writer.CloseBrace();
    }

    private static string DescriptorCall(string id, string version, bool idempotent, string[] sideEffects)
    {
        var effects = sideEffects.Length == 0
            ? string.Empty
            : ", " + string.Join(", ", sideEffects.Select(Quote));

        return "CapabilityDescriptor.Create(" + Quote(id) + ", " + Quote(version) + ", " +
               (idempotent ? "true" : "false") + effects + ")";
    }

    private static void EmitPlan(SourceWriter writer, FlowModel flow)
    {
        writer.Line("/// <summary>The compiled execution plan. Built once, shared by every invocation.</summary>");
        writer.Line("public static ExecutionPlan Plan { get; } = ExecutionPlan.Create(");
        writer.Line("    FlowDescriptor.Create(");
        writer.Line("        " + Quote(flow.FlowId) + ",");
        writer.Line("        " + Quote(flow.Version) + ",");
        writer.Line("        ExecutionProfile." + flow.Profile + ",");
        writer.Line("        " + DeadlineExpression(flow.Deadline) + "),");
        writer.Line("    StepGraph.Create(new StepNode[]");
        writer.Line("    {");

        foreach (var step in flow.Steps)
        {
            writer.Line("        " + StepNodeExpression(step) + ",");
        }

        writer.Line("    }));");
    }

    private static string StepNodeExpression(StepModel step)
    {
        switch (step.Kind)
        {
            case StepKindModel.Emit:
                return "StepNode.ForEmit(" + step.Index + ", " + Quote(step.EventType!) + ")";

            case StepKindModel.AwaitSignal:
                return "StepNode.ForAwaitSignal(" + step.Index + ", " + Quote(step.SignalType!) +
                       ", TimeSpan.FromHours(1))";

            default:
                var compensation = step.IsCompensable
                    ? ", Descriptors.Step" + step.Index + "Compensation"
                    : string.Empty;

                return "StepNode.ForCapability(" + step.Index + ", Descriptors.Step" + step.Index +
                       compensation + ")";
        }
    }

    private static string DeadlineExpression(string? iso8601)
    {
        // A flow without an explicit deadline gets thirty seconds. Stated here rather
        // than defaulted silently in the runtime: an unbounded flow is not a default
        // anyone would choose deliberately.
        return iso8601 == null
            ? "TimeSpan.FromSeconds(30)"
            : "System.Xml.XmlConvert.ToTimeSpan(" + Quote(iso8601) + ")";
    }

    private static void EmitDispatcher(SourceWriter writer, FlowModel flow)
    {
        writer.Line("/// <summary>Invokes the capability behind each step index.</summary>");
        writer.Line("/// <remarks>");
        writer.Line("/// A switch, not a lookup. The engine's loop cannot know each step's types;");
        writer.Line("/// this class does, which is why nothing here is boxed and no reflection runs.");
        writer.Line("/// </remarks>");
        writer.Line("public sealed class Dispatcher : IStepDispatcher");
        writer.OpenBrace();

        EmitDispatcherFields(writer, flow);
        writer.Line();
        EmitDispatcherConstructor(writer, flow);
        writer.Line();
        EmitDispatcherExecute(writer, flow);
        writer.Line();
        EmitDispatcherCompensate(writer, flow);

        writer.CloseBrace();
    }

    private static void EmitDispatcherFields(SourceWriter writer, FlowModel flow)
    {
        foreach (var capability in flow.ReferencedCapabilities)
        {
            writer.Line("private readonly " + capability + " " + FieldName(capability) + ";");
        }
    }

    private static void EmitDispatcherConstructor(SourceWriter writer, FlowModel flow)
    {
        var parameters = string.Join(
            ", ",
            flow.ReferencedCapabilities.Select(c => c + " " + ParameterName(c)));

        writer.Line("/// <summary>Capabilities are injected, never resolved by reflection.</summary>");
        writer.Line("public Dispatcher(" + parameters + ")");
        writer.OpenBrace();

        foreach (var capability in flow.ReferencedCapabilities)
        {
            writer.Line(FieldName(capability) + " = " + ParameterName(capability) + ";");
        }

        writer.CloseBrace();
    }

    private static void EmitDispatcherExecute(SourceWriter writer, FlowModel flow)
    {
        writer.Line("/// <inheritdoc />");
        writer.Line("public async ValueTask<StepOutcome> ExecuteAsync(int stepIndex, FlowContext ctx, CancellationToken ct)");
        writer.OpenBrace();
        writer.Line("switch (stepIndex)");
        writer.OpenBrace();

        foreach (var step in flow.Steps)
        {
            writer.Line("case " + step.Index + ":");
            writer.OpenBrace();

            if (step.Kind == StepKindModel.Capability)
            {
                EmitCapabilityInvocation(writer, FieldName(step.CapabilityTypeName!), step.Location);
            }
            else
            {
                // Emit and AwaitSignal have no capability to call; the engine and the
                // event plugin handle them. Returning success keeps the switch total.
                writer.Line("return StepOutcome.Success;");
            }

            writer.CloseBrace();
        }

        writer.Line("default:");
        writer.OpenBrace();
        writer.Line("throw new ArgumentOutOfRangeException(");
        writer.Line("    nameof(stepIndex),");
        writer.Line("    stepIndex,");
        writer.Line("    \"Step index is outside the compiled plan. The plan and this dispatcher \" +");
        writer.Line("    \"are generated together, so this means they came from different builds.\");");
        writer.CloseBrace();

        writer.CloseBrace();
        writer.CloseBrace();
    }

    private static void EmitCapabilityInvocation(SourceWriter writer, string field, string? location)
    {
        EmitLineDirective(writer, location);
        writer.Line("var result = await " + field + ".ExecuteAsync(ctx.Input, ctx, ct).ConfigureAwait(false);");
        EmitLineDirectiveEnd(writer, location);
        writer.Line("return result.IsSuccess ? StepOutcome.Success : StepOutcome.Failed(result.Error);");
    }

    private static void EmitDispatcherCompensate(SourceWriter writer, FlowModel flow)
    {
        writer.Line("/// <inheritdoc />");
        writer.Line("public async ValueTask<StepOutcome> CompensateAsync(int stepIndex, FlowContext ctx, CancellationToken ct)");
        writer.OpenBrace();
        writer.Line("switch (stepIndex)");
        writer.OpenBrace();

        foreach (var step in flow.Steps.Where(s => s.IsCompensable))
        {
            writer.Line("case " + step.Index + ":");
            writer.OpenBrace();
            EmitCapabilityInvocation(writer, FieldName(step.CompensationTypeName!), step.Location);
            writer.CloseBrace();
        }

        writer.Line("default:");
        writer.OpenBrace();
        writer.Line("// The engine only compensates steps that declared one, so reaching");
        writer.Line("// here means the plan and this dispatcher disagree.");
        writer.Line("return StepOutcome.Success;");
        writer.CloseBrace();

        writer.CloseBrace();
        writer.CloseBrace();
    }

    private static void EmitLineDirective(SourceWriter writer, string? location)
    {
        if (location == null)
        {
            return;
        }

        var separator = location.LastIndexOf(':');

        if (separator <= 0)
        {
            return;
        }

        var file = location.Substring(0, separator);
        var line = location.Substring(separator + 1);

        // Maps the emitted call back to the .Step<T>() that declared it, so a
        // breakpoint and a stack trace both land in the developer's own file.
        writer.Line("#line " + line + " \"" + file.Replace("\\", "\\\\") + "\"");
    }

    private static void EmitLineDirectiveEnd(SourceWriter writer, string? location)
    {
        if (location != null)
        {
            writer.Line("#line default");
        }
    }

    private static string FieldName(string fullTypeName) => "_" + ParameterName(fullTypeName);

    private static string ParameterName(string fullTypeName)
    {
        var simple = fullTypeName;
        var lastDot = simple.LastIndexOf('.');

        if (lastDot >= 0)
        {
            simple = simple.Substring(lastDot + 1);
        }

        return simple.Length == 0
            ? "capability"
            : char.ToLowerInvariant(simple[0]) + simple.Substring(1);
    }

    private static string Quote(string value) =>
        "\"" + value.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
}
