using System.Globalization;
using System.Linq;
using FlowX.Compiler.Model;

namespace FlowX.Compiler.Emit;

/// <summary>
/// Turns a <see cref="FlowModel"/> into the C# a flow needs at run time: its
/// compiled <c>ExecutionPlan</c> and its <c>IStepDispatcher</c>.
/// </summary>
/// <remarks>
/// <para>
/// Pure. Takes a model, returns a string, touches nothing else — which is what
/// makes every emitted shape testable by comparing text, with no compilation and
/// no Roslyn host. That is the second half of the R1 mitigation.
/// </para>
/// <para>
/// The emitted dispatcher is the reason the engine can stay type-agnostic. It holds
/// each step's typed input and output in its own fields and switches on the step
/// index, so nothing is boxed and the engine never learns what a
/// <c>ReserveRequest</c> is. See <c>IStepDispatcher</c> for why that split exists.
/// </para>
/// </remarks>
public static class FlowEmitter
{
    /// <summary>The header every generated file carries.</summary>
    public const string Header =
        "// <auto-generated>\n" +
        "//     Generated by FlowX.Compiler from the Define method of this flow.\n" +
        "//\n" +
        "//     This file is real C#, on disk, with line directives back to your source.\n" +
        "//     Set a breakpoint in it. If it is hard to read, that is a bug in the\n" +
        "//     generator, not something you are supposed to put up with.\n" +
        "// </auto-generated>\n";

    /// <summary>The file name this model's generated source should be written to.</summary>
    public static string FileNameFor(FlowModel flow)
    {
        if (flow is null)
        {
            throw new System.ArgumentNullException(nameof(flow));
        }

        return flow.FullTypeName + ".Flow.g.cs";
    }

    /// <summary>Emits the plan and dispatcher for one flow.</summary>
    public static string Emit(FlowModel flow)
    {
        if (flow is null)
        {
            throw new System.ArgumentNullException(nameof(flow));
        }

        var writer = new SourceWriter();

        writer.Line(Header.TrimEnd('\n'));
        writer.Line("#nullable enable");
        writer.Line();
        writer.Line("using System;");
        writer.Line("using System.Threading;");
        writer.Line("using System.Threading.Tasks;");
        writer.Line("using FlowX;");
        writer.Line("using FlowX.Runtime;");

        // The author's usings, so a copied .Return(...) lambda resolves the same names
        // here that it resolved where it was written. Skipped when already emitted above.
        foreach (var directive in flow.Usings.Where(u => !EmittedUsings.Contains(u)))
        {
            writer.Line(directive);
        }

        writer.Line();

        var hasNamespace = !string.IsNullOrEmpty(flow.ContainingNamespace);

        if (hasNamespace)
        {
            writer.Line("namespace " + flow.ContainingNamespace);
            writer.OpenBrace();
        }

        EmitFlowPartial(writer, flow);

        if (hasNamespace)
        {
            writer.CloseBrace();
        }

        return writer.ToString();
    }

    private static void EmitFlowPartial(SourceWriter writer, FlowModel flow)
    {
        writer.Line("/// <summary>Compiled plan and dispatcher for <c>" + flow.FlowId + "</c>.</summary>");
        writer.Line("partial class " + flow.TypeName);
        writer.OpenBrace();

        EmitDescriptors(writer, flow);
        writer.Line();
        EmitConditions(writer, flow);
        EmitSelectors(writer, flow);
        EmitPlan(writer, flow);
        writer.Line();
        EmitProjection(writer, flow);
        EmitSensitiveMembers(writer, flow);
        EmitDispatcher(writer, flow);

        writer.CloseBrace();
    }

    /// <summary>
    /// Emits the flow's output projection from its <c>.Return(...)</c> clause.
    /// </summary>
    /// <remarks>
    /// A <c>static readonly</c> field, not a method or a lambda built per call: the engine
    /// takes it as a <c>Func</c>, and a field is allocated once at type initialisation, so
    /// passing it costs nothing and the zero-allocation budget survives contact with the
    /// feature that gives a flow an answer to return.
    /// </remarks>
    private static void EmitProjection(SourceWriter writer, FlowModel flow)
    {
        if (flow.ReturnProjection is null)
        {
            return;
        }

        writer.Line("/// <summary>Projects the flow's output from the finished context.</summary>");
        writer.Line("/// <remarks>");
        writer.Line("/// Your <c>.Return(...)</c> expression, copied verbatim. The engine runs it while");
        writer.Line("/// the pooled context is still rented, which is why it can read the context at all.");
        writer.Line("/// </remarks>");
        EmitLineDirective(writer, flow.ReturnLocation);
        writer.Line(
            "public static readonly Func<FlowContext, " + flow.OutputTypeName + "> Projection = " +
            flow.ReturnProjection + ";");
        EmitLineDirectiveEnd(writer, flow.ReturnLocation);
        writer.Line();
    }

    /// <summary>
    /// Emits the names of the contract members marked <c>[Sensitive]</c>.
    /// </summary>
    /// <remarks>
    /// This is what turns the attribute from a fact recorded in the manifest into
    /// something a transport can act on. The endpoint uses it to strip matching keys out
    /// of a Problem Details body, which is the only path in this release that serialises
    /// anything a capability attached to an error.
    /// <para>
    /// Emitted even when empty, unlike the manifest's array: a caller passing
    /// <c>Flow.SensitiveMembers</c> must not have to know whether the flow has any, and a
    /// missing field would be a compile error rather than an empty guard.
    /// </para>
    /// </remarks>
    private static void EmitSensitiveMembers(SourceWriter writer, FlowModel flow)
    {
        var members = flow.SensitiveInputMembers
            .Concat(flow.SensitiveOutputMembers)
            .Distinct()
            .OrderBy(m => m, System.StringComparer.Ordinal)
            .ToList();

        writer.Line("/// <summary>Contract members declared <c>[Sensitive]</c>, ordinally sorted.</summary>");
        writer.Line("/// <remarks>");
        writer.Line("/// Pass to <c>MapFlow</c> so their values are stripped from an error response.");
        writer.Line("/// </remarks>");
        writer.Line(
            "public static readonly string[] SensitiveMembers = " +
            (members.Count == 0
                ? "System.Array.Empty<string>();"
                : "new[] { " + string.Join(", ", members.Select(m => "\"" + m + "\"")) + " };"));
        writer.Line();
    }

    /// <summary>Usings the generated file always carries, so copied ones are not repeated.</summary>
    private static readonly System.Collections.Generic.HashSet<string> EmittedUsings =
        new System.Collections.Generic.HashSet<string>(System.StringComparer.Ordinal)
        {
            "using System;",
            "using System.Threading;",
            "using System.Threading.Tasks;",
            "using FlowX;",
            "using FlowX.Runtime;",
        };

    /// <summary>
    /// Emits one <c>static readonly</c> delegate per <c>.When(...)</c> predicate.
    /// </summary>
    /// <remarks>
    /// A field, initialised once at type initialisation, for exactly the reason
    /// <c>Projection</c> is one: the engine's step loop must not allocate, and a lambda
    /// built at the call site would cost a delegate per branch per execution. Budget B2 is
    /// a hard zero, so a conditional flow would have failed it on the first commit.
    /// <para>
    /// The predicate is the author's own expression, copied verbatim inside a
    /// <c>#line</c> pair, so a breakpoint on the condition lands on the condition they
    /// wrote and a wrong-branch bug is debuggable rather than archaeological.
    /// </para>
    /// </remarks>
    private static void EmitConditions(SourceWriter writer, FlowModel flow)
    {
        var conditions = flow.AllSteps.Where(s => s.Kind == StepKindModel.Condition).ToList();

        if (conditions.Count == 0)
        {
            return;
        }

        writer.Line("/// <summary>Branch predicates, built once at type initialisation.</summary>");
        writer.Line("/// <remarks>");
        writer.Line("/// Each is your <c>.When(...)</c> expression, copied verbatim. They are pure and");
        writer.Line("/// synchronous by design: a condition may read only the context, the flow input");
        writer.Line("/// and prior step results, so that a replay takes the branch it took before.");
        writer.Line("/// </remarks>");
        writer.Line("private static class Conditions");
        writer.OpenBrace();

        foreach (var condition in conditions.OrderBy(c => c.Index))
        {
            EmitLineDirective(writer, condition.PredicateLocation);
            writer.Line(
                "public static readonly Func<FlowContext, bool> Step" + condition.Index + " = " +
                condition.Predicate + ";");
            EmitLineDirectiveEnd(writer, condition.PredicateLocation);
        }

        writer.CloseBrace();
        writer.Line();
    }

    /// <summary>
    /// Emits one <c>static readonly</c> delegate per <c>.Switch(...)</c> selector.
    /// </summary>
    /// <remarks>
    /// A field, for the same reason the predicates are: budget B2 is a hard zero, and a
    /// lambda built at the switch would cost a delegate per execution. Typed at the value
    /// the selector actually produces, so <c>Select</c> below can compare against it
    /// without boxing.
    /// </remarks>
    private static void EmitSelectors(SourceWriter writer, FlowModel flow)
    {
        var switches = Switches(flow);

        if (switches.Count == 0)
        {
            return;
        }

        writer.Line("/// <summary>Switch selectors, built once at type initialisation.</summary>");
        writer.Line("/// <remarks>");
        writer.Line("/// Each is your <c>.Switch(...)</c> expression, copied verbatim. They obey the same");
        writer.Line("/// determinism rule as a condition — context, flow input and prior step results");
        writer.Line("/// only — so that a replay selects the case it selected before.");
        writer.Line("/// </remarks>");
        writer.Line("private static class Selectors");
        writer.OpenBrace();

        foreach (var step in switches)
        {
            EmitLineDirective(writer, step.SelectorLocation);
            writer.Line(
                "public static readonly Func<FlowContext, " + step.SelectorTypeName + "> Step" + step.Index +
                " = " + step.Selector + ";");
            EmitLineDirectiveEnd(writer, step.SelectorLocation);
        }

        writer.CloseBrace();
        writer.Line();
    }

    /// <summary>The flow's value branches, ascending by flat index.</summary>
    private static System.Collections.Generic.List<StepModel> Switches(FlowModel flow) => flow.AllSteps
        .Where(s => s.Kind == StepKindModel.Switch)
        .OrderBy(s => s.Index)
        .ToList();

    private static void EmitDescriptors(SourceWriter writer, FlowModel flow)
    {
        writer.Line("/// <summary>Capability descriptors, built once at type initialisation.</summary>");
        writer.Line("private static class Descriptors");
        writer.OpenBrace();

        foreach (var step in flow.AllSteps.Where(s => s.Kind == StepKindModel.Capability))
        {
            writer.Line(
                "public static readonly CapabilityDescriptor Step" + step.Index + " = " +
                DescriptorCall(step.CapabilityId!, step.CapabilityVersion!, step.IsIdempotent, step.SideEffects) + ";");

            if (step.IsCompensable)
            {
                writer.Line(
                    "public static readonly CapabilityDescriptor Step" + step.Index + "Compensation = " +
                    DescriptorCall(step.CompensationId!, step.CompensationVersion!, true, System.Array.Empty<string>()) + ";");
            }
        }

        writer.CloseBrace();
    }

    private static string DescriptorCall(string id, string version, bool idempotent, string[] sideEffects)
    {
        var effects = sideEffects.Length == 0
            ? string.Empty
            : ", " + string.Join(", ", sideEffects.Select(Quote));

        return "CapabilityDescriptor.Create(" + Quote(id) + ", " + Quote(version) + ", " +
               (idempotent ? "true" : "false") + effects + ")";
    }

    private static void EmitPlan(SourceWriter writer, FlowModel flow)
    {
        writer.Line("/// <summary>The compiled execution plan. Built once, shared by every invocation.</summary>");
        writer.Line("public static ExecutionPlan Plan { get; } = ExecutionPlan.Create(");
        writer.Line("    FlowDescriptor.Create(");
        writer.Line("        " + Quote(flow.FlowId) + ",");
        writer.Line("        " + Quote(flow.Version) + ",");
        writer.Line("        ExecutionProfile." + flow.Profile + ",");
        writer.Line("        " + DeadlineExpression(flow.Deadline) + "),");
        writer.Line("    StepGraph.Create(new StepNode[]");
        writer.Line("    {");

        EmitStepNodes(writer, flow.Steps);

        writer.Line("    }));");
    }

    /// <summary>
    /// Writes the step array, flattening conditionals into branch-and-jump form.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The layout is <c>branch · then… · jump · otherwise…</c>. The branch carries only
    /// its false target, because the <c>then</c> block starts at the very next index; the
    /// jump exists solely so a taken <c>then</c> block skips the alternative, and is
    /// omitted when there is no alternative to skip. Nested conditionals recurse, and
    /// their indices were already assigned in this same order during analysis — which is
    /// why the array comes out contiguous and <c>StepGraph.Create</c> accepts it.
    /// </para>
    /// <para>
    /// A switch is the same shape with more blocks:
    /// <c>switch · case₀… · jump · case₁… · jump · … · default…</c>. Each block is closed
    /// by a jump to the join, except the last non-empty one, which falls into the join
    /// anyway.
    /// </para>
    /// </remarks>
    private static void EmitStepNodes(SourceWriter writer, System.Collections.Generic.IReadOnlyList<StepModel> steps)
    {
        foreach (var step in steps)
        {
            switch (step.Kind)
            {
                case StepKindModel.Condition:
                    writer.Line("        StepNode.ForBranch(" + step.Index + ", " + step.FalseTarget + "),");
                    EmitStepNodes(writer, step.Then);

                    if (step.JumpIndex is int jump)
                    {
                        writer.Line("        StepNode.ForJump(" + jump + ", " + step.JoinIndex + "),");
                        EmitStepNodes(writer, step.Otherwise);
                    }

                    break;

                case StepKindModel.Switch:
                    writer.Line("        " + SwitchNodeExpression(step) + ",");

                    foreach (var arm in step.Cases)
                    {
                        EmitStepNodes(writer, arm.Steps);

                        if (arm.JumpIndex is int caseJump)
                        {
                            writer.Line("        StepNode.ForJump(" + caseJump + ", " + step.JoinIndex + "),");
                        }
                    }

                    EmitStepNodes(writer, step.Default);
                    break;

                default:
                    writer.Line("        " + StepNodeExpression(step) + ",");
                    break;
            }
        }
    }

    private static string SwitchNodeExpression(StepModel step)
    {
        var targets = string.Join(
            ", ",
            step.Cases.Select(c => c.Target.ToString(CultureInfo.InvariantCulture)));

        return "StepNode.ForSwitch(" + step.Index + ", new[] { " + targets + " }, defaultTarget: " +
               step.DefaultTarget + ")";
    }

    private static string StepNodeExpression(StepModel step)
    {
        switch (step.Kind)
        {
            case StepKindModel.Emit:
                return "StepNode.ForEmit(" + step.Index + ", " + Quote(step.EventType!) + ")";

            case StepKindModel.AwaitSignal:
                return "StepNode.ForAwaitSignal(" + step.Index + ", " + Quote(step.SignalType!) +
                       ", TimeSpan.FromHours(1))";

            default:
                var compensation = step.IsCompensable
                    ? ", Descriptors.Step" + step.Index + "Compensation"
                    : string.Empty;

                return "StepNode.ForCapability(" + step.Index + ", Descriptors.Step" + step.Index +
                       compensation + ")";
        }
    }

    private static string DeadlineExpression(string? iso8601)
    {
        // A flow without an explicit deadline gets thirty seconds. Stated here rather
        // than defaulted silently in the runtime: an unbounded flow is not a default
        // anyone would choose deliberately.
        return iso8601 == null
            ? "TimeSpan.FromSeconds(30)"
            : "System.Xml.XmlConvert.ToTimeSpan(" + Quote(iso8601) + ")";
    }

    private static void EmitDispatcher(SourceWriter writer, FlowModel flow)
    {
        writer.Line("/// <summary>Invokes the capability behind each step index.</summary>");
        writer.Line("/// <remarks>");
        writer.Line("/// A switch, not a lookup. The engine's loop cannot know each step's types;");
        writer.Line("/// this class does, which is why nothing here is boxed and no reflection runs.");
        writer.Line("/// </remarks>");
        writer.Line("public sealed class Dispatcher : IStepDispatcher");
        writer.OpenBrace();

        EmitDispatcherFields(writer, flow);
        writer.Line();
        EmitDispatcherConstructor(writer, flow);
        writer.Line();
        EmitDispatcherExecute(writer, flow);
        writer.Line();
        EmitDispatcherCompensate(writer, flow);
        writer.Line();
        EmitDispatcherEvaluate(writer, flow);
        writer.Line();
        EmitDispatcherSelect(writer, flow);

        writer.CloseBrace();
    }

    private static void EmitDispatcherFields(SourceWriter writer, FlowModel flow)
    {
        foreach (var capability in flow.ReferencedCapabilities)
        {
            writer.Line("private readonly " + capability + " " + FieldName(capability) + ";");
        }
    }

    private static void EmitDispatcherConstructor(SourceWriter writer, FlowModel flow)
    {
        var parameters = string.Join(
            ", ",
            flow.ReferencedCapabilities.Select(c => c + " " + ParameterName(c)));

        writer.Line("/// <summary>Capabilities are injected, never resolved by reflection.</summary>");
        writer.Line("public Dispatcher(" + parameters + ")");
        writer.OpenBrace();

        foreach (var capability in flow.ReferencedCapabilities)
        {
            writer.Line(FieldName(capability) + " = " + ParameterName(capability) + ";");
        }

        writer.CloseBrace();
    }

    private static void EmitDispatcherExecute(SourceWriter writer, FlowModel flow)
    {
        writer.Line("/// <inheritdoc />");
        writer.Line("public async ValueTask<StepOutcome> ExecuteAsync(int stepIndex, FlowContext ctx, CancellationToken ct)");
        writer.OpenBrace();
        writer.Line("switch (stepIndex)");
        writer.OpenBrace();

        // Conditions and switches have no case: the engine reaches them through Evaluate
        // and Select, never through ExecuteAsync, so a case here would be dead code in the
        // file the header promises is readable.
        foreach (var step in flow.AllSteps
            .Where(s => s.Kind is not (StepKindModel.Condition or StepKindModel.Switch))
            .OrderBy(s => s.Index))
        {
            writer.Line("case " + step.Index + ":");
            writer.OpenBrace();

            if (step.Kind == StepKindModel.Capability)
            {
                EmitCapabilityInvocation(
                    writer,
                    FieldName(step.CapabilityTypeName!),
                    step.CapabilityInput,
                    step.CapabilityOutput,
                    step.Location);
            }
            else
            {
                // Emit and AwaitSignal have no capability to call; the engine and the
                // event plugin handle them. Returning success keeps the switch total.
                writer.Line("return StepOutcome.Success;");
            }

            writer.CloseBrace();
        }

        writer.Line("default:");
        writer.OpenBrace();
        writer.Line("throw new ArgumentOutOfRangeException(");
        writer.Line("    nameof(stepIndex),");
        writer.Line("    stepIndex,");
        writer.Line("    \"Step index is outside the compiled plan. The plan and this dispatcher \" +");
        writer.Line("    \"are generated together, so this means they came from different builds.\");");
        writer.CloseBrace();

        writer.CloseBrace();
        writer.CloseBrace();
    }

    private static void EmitCapabilityInvocation(
        SourceWriter writer,
        string field,
        string? inputType,
        string? outputType,
        string? location)
    {
        // Step inputs are bound by type out of the flow's state bag. The flow's own
        // input is seeded there by the engine; every later step reads what an earlier
        // one returned. That is what lets a chain of differently-typed steps run
        // through an engine that knows none of the types.
        var input = inputType is null ? "ctx" : "ctx.Get<" + inputType + ">()";

        EmitLineDirective(writer, location);
        writer.Line("var result = await " + field + ".ExecuteAsync(" + input + ", ctx, ct).ConfigureAwait(false);");
        EmitLineDirectiveEnd(writer, location);

        writer.Line("if (!result.IsSuccess)");
        writer.OpenBrace();
        writer.Line("return StepOutcome.Failed(result.Error);");
        writer.CloseBrace();
        writer.Line();

        if (outputType is not null)
        {
            // Stored so the next step can bind to it.
            writer.Line("ctx.Set(result.Value);");
        }

        writer.Line("return StepOutcome.Success;");
    }

    private static void EmitDispatcherCompensate(SourceWriter writer, FlowModel flow)
    {
        writer.Line("/// <inheritdoc />");
        writer.Line("public async ValueTask<StepOutcome> CompensateAsync(int stepIndex, FlowContext ctx, CancellationToken ct)");
        writer.OpenBrace();
        writer.Line("switch (stepIndex)");
        writer.OpenBrace();

        foreach (var step in flow.AllSteps.Where(s => s.IsCompensable).OrderBy(s => s.Index))
        {
            writer.Line("case " + step.Index + ":");
            writer.OpenBrace();

            // The compensation binds to the step's own input — the thing it has to undo.
            EmitCapabilityInvocation(
                writer,
                FieldName(step.CompensationTypeName!),
                step.CapabilityInput,
                outputType: null,
                step.Location);

            writer.CloseBrace();
        }

        writer.Line("default:");
        writer.OpenBrace();
        writer.Line("// The engine only compensates steps that declared one, so reaching");
        writer.Line("// here means the plan and this dispatcher disagree.");
        writer.Line("return StepOutcome.Success;");
        writer.CloseBrace();

        writer.CloseBrace();
        writer.CloseBrace();
    }

    private static void EmitDispatcherEvaluate(SourceWriter writer, FlowModel flow)
    {
        var conditions = flow.AllSteps
            .Where(s => s.Kind == StepKindModel.Condition)
            .OrderBy(s => s.Index)
            .ToList();

        writer.Line("/// <inheritdoc />");
        writer.Line("public bool Evaluate(int stepIndex, FlowContext ctx)");
        writer.OpenBrace();

        if (conditions.Count == 0)
        {
            // No switch at all rather than one with only a default. A flow with no
            // conditional has no branch for the engine to ask about, and an empty switch
            // reads like an oversight.
            writer.Line("throw new ArgumentOutOfRangeException(");
            writer.Line("    nameof(stepIndex),");
            writer.Line("    stepIndex,");
            writer.Line("    \"This flow declares no conditional, so the engine never asks it to \" +");
            writer.Line("    \"evaluate one. Reaching this means the plan and this dispatcher came \" +");
            writer.Line("    \"from different builds.\");");
            writer.CloseBrace();
            return;
        }

        writer.Line("switch (stepIndex)");
        writer.OpenBrace();

        foreach (var condition in conditions)
        {
            writer.Line("case " + condition.Index + ":");
            writer.OpenBrace();
            writer.Line("return Conditions.Step" + condition.Index + "(ctx);");
            writer.CloseBrace();
        }

        writer.Line("default:");
        writer.OpenBrace();
        writer.Line("throw new ArgumentOutOfRangeException(");
        writer.Line("    nameof(stepIndex),");
        writer.Line("    stepIndex,");
        writer.Line("    \"Step index does not name a branch in the compiled plan. The plan and \" +");
        writer.Line("    \"this dispatcher are generated together, so this means they came from \" +");
        writer.Line("    \"different builds.\");");
        writer.CloseBrace();

        writer.CloseBrace();
        writer.CloseBrace();
    }

    /// <summary>
    /// Emits <c>Select</c>: which case of each switch matched, by step index.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The selector runs <em>once</em> and the arms are then tested against the value it
    /// produced. Compiling a switch into a chain of equality predicates would have read
    /// the selector once per arm, which is wrong for a reader and wasteful for a machine.
    /// </para>
    /// <para>
    /// The comparison is <c>EqualityComparer&lt;T&gt;.Default.Equals</c> rather than a C#
    /// <c>switch</c> statement, because a case value is an arbitrary expression and a
    /// <c>case</c> label demands a compile-time constant — <c>.Case(Channel.Retail, …)</c>
    /// would compile and <c>.Case(_defaults.Channel, …)</c> would not. The comparer is a
    /// cached static at the real type, so an <c>enum</c>, an <c>int</c> and a
    /// <c>string</c> all compare without boxing and the arm costs nothing to take.
    /// </para>
    /// </remarks>
    private static void EmitDispatcherSelect(SourceWriter writer, FlowModel flow)
    {
        var switches = Switches(flow);

        writer.Line("/// <inheritdoc />");
        writer.Line("public int Select(int stepIndex, FlowContext ctx)");
        writer.OpenBrace();

        if (switches.Count == 0)
        {
            writer.Line("throw new ArgumentOutOfRangeException(");
            writer.Line("    nameof(stepIndex),");
            writer.Line("    stepIndex,");
            writer.Line("    \"This flow declares no switch, so the engine never asks it to select a \" +");
            writer.Line("    \"case. Reaching this means the plan and this dispatcher came from \" +");
            writer.Line("    \"different builds.\");");
            writer.CloseBrace();
            return;
        }

        writer.Line("switch (stepIndex)");
        writer.OpenBrace();

        foreach (var step in switches)
        {
            writer.Line("case " + step.Index + ":");
            writer.OpenBrace();
            writer.Line("var value = Selectors.Step" + step.Index + "(ctx);");

            for (var arm = 0; arm < step.Cases.Count; arm++)
            {
                writer.Line();
                EmitLineDirective(writer, step.Cases[arm].ValueLocation);
                writer.Line(
                    "if (System.Collections.Generic.EqualityComparer<" + step.SelectorTypeName +
                    ">.Default.Equals(value, " + step.Cases[arm].Value + "))");
                writer.OpenBrace();
                writer.Line("return " + arm.ToString(CultureInfo.InvariantCulture) + ";");
                writer.CloseBrace();
                EmitLineDirectiveEnd(writer, step.Cases[arm].ValueLocation);
            }

            writer.Line();
            writer.Line("// No case matched. The engine takes the switch's default target,");
            writer.Line("// which is the `Default` block when there is one and the join when");
            writer.Line("// there is not — a value nothing matched simply continues.");
            writer.Line("return -1;");
            writer.CloseBrace();
        }

        writer.Line("default:");
        writer.OpenBrace();
        writer.Line("throw new ArgumentOutOfRangeException(");
        writer.Line("    nameof(stepIndex),");
        writer.Line("    stepIndex,");
        writer.Line("    \"Step index does not name a switch in the compiled plan. The plan and \" +");
        writer.Line("    \"this dispatcher are generated together, so this means they came from \" +");
        writer.Line("    \"different builds.\");");
        writer.CloseBrace();

        writer.CloseBrace();
        writer.CloseBrace();
    }

    private static void EmitLineDirective(SourceWriter writer, string? location)
    {
        if (location == null)
        {
            return;
        }

        var separator = location.LastIndexOf(':');

        if (separator <= 0)
        {
            return;
        }

        var file = location.Substring(0, separator);
        var line = location.Substring(separator + 1);

        // Maps the emitted call back to the .Step<T>() that declared it, so a
        // breakpoint and a stack trace both land in the developer's own file.
        writer.Line("#line " + line + " \"" + file.Replace("\\", "\\\\") + "\"");
    }

    private static void EmitLineDirectiveEnd(SourceWriter writer, string? location)
    {
        if (location != null)
        {
            writer.Line("#line default");
        }
    }

    private static string FieldName(string fullTypeName) => "_" + ParameterName(fullTypeName);

    private static string ParameterName(string fullTypeName)
    {
        var simple = fullTypeName;
        var lastDot = simple.LastIndexOf('.');

        if (lastDot >= 0)
        {
            simple = simple.Substring(lastDot + 1);
        }

        return simple.Length == 0
            ? "capability"
            : char.ToLowerInvariant(simple[0]) + simple.Substring(1);
    }

    private static string Quote(string value) =>
        "\"" + value.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
}
